### ISSUE TITLE
Frequent crashes - DCPProfile::Apply and MultiDiagonalSymmetricMatrix::CholeskyBackSolve

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1301]
Originally reported on Google Code with ID 1317
```
Right-click on a thumbnail, clear from cache > full.
Right-click on a thumbnail, apply the neutral profile.
Open it, zoom to 100%.
Enable tonemapping,
Enable highlight reconstruction. RT segfaults.

The tonemapping and HR are not necessary - sometimes it would segfault as soon as I
zoom to 100%.

It only does this on some photos:
http://rawtherapee.com/shared/test_images/amsterdam.pef
http://rawtherapee.com/shared/test_images/colorspace_flowers.pef

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcc91b700 (LWP 996)]
0x00000000009f9f1c in rtengine::DCPProfile::Apply (.omp_data_i=0x7fffd77fd130) at /home/drslony/rawtherapee/rtengine/dcp.cc:227
227                             hFract1 * entry01->fHueShift;

#0  0x00000000009f9f1c in rtengine::DCPProfile::Apply (.omp_data_i=0x7fffbaff4130)
at /home/drslony/rawtherapee/rtengine/dcp.cc:227
#1  0x00007ffff256d7e2 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.5.3/libgomp.so.1
#2  0x00007ffff2139c5c in start_thread () from /lib64/libpthread.so.0
#3  0x00007ffff1e80fcd in clone () from /lib64/libc.so.6

Sometimes it crashes with this:
Error in MultiDiagonalSymmetricMatrix::CreateIncompleteCholeskyFactorization: division
by zero. Matrix not decomposable.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc24e2700 (LWP 2339)]
0x00000000008ab553 in rtengine::MultiDiagonalSymmetricMatrix::CholeskyBackSolve (this=0x7fff9c0091d0,
x=0x7fff9d0e98d0, b=0x7fff9cea03d0) at /home/drslony/rawtherapee/rtengine/EdgePreservingDecomposition.cc:285
285             float **d = IncompleteCholeskyFactorization->Diagonals;


Branch: default
Version: 4.0.8.6
Changeset: 952a99e79816
Compiler: GCC 4.5.3
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.2
Build type: debug
Build flags:  -march=native
Link flags:   -march=native
OpenMP support: ON
MMAP support: ON
```

Reported by `entertheyoni` on 2012-04-08 16:35:52

**Comment by Beep6581** [comment]
Haven't encountered this issue in ages, closing.
