### ISSUE TITLE
Segfault when set a star rating after renaming image

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1716]
Originally reported on Google Code with ID 1732

```
How to reproduce:

- Choose a unrated image from image browser and open it.
- Switch back to the browser and rename the image to something other.
- Close the image editing tab for the previously opened image.
- From the image browser, set a star rating for the renamed image.
- segfault.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000882952 in Thumbnail::notifylisterners_procParamsChanged (this=0x7fffd0004000,

    whoChangedIt=1) at /home/cytrinox/src/rawtherapee/rtgui/thumbnail.cc:217
217                     listeners[i]->procParamsChanged (this, whoChangedIt);



(gdb) backtrace
#0  0x0000000000882952 in Thumbnail::notifylisterners_procParamsChanged (this=0x7fffd0004000,

    whoChangedIt=1) at /home/cytrinox/src/rawtherapee/rtgui/thumbnail.cc:217
#1  0x0000000000710e5a in FileBrowser::rankingRequested (this=0x32e9010, 
    tbe=std::vector of length 1, capacity 1 = {...}, rank=5)
    at /home/cytrinox/src/rawtherapee/rtgui/filebrowser.cc:1018
#2  0x00000000007111a7 in FileBrowser::buttonPressed (this=0x32e9010, button=0x38b1770,
actionCode=5, 
    actionData=0x7fffdc0089c0) at /home/cytrinox/src/rawtherapee/rtgui/filebrowser.cc:1053
#3  0x00000000008b2e97 in LWButton::releaseNotify (this=0x38b1770, x=417, y=19)
    at /home/cytrinox/src/rawtherapee/rtgui/lwbutton.cc:142
#4  0x00000000008b3a36 in LWButtonSet::releaseNotify (this=0x3981310, x=417, y=19)
    at /home/cytrinox/src/rawtherapee/rtgui/lwbuttonset.cc:129
#5  0x00000000008aa6ce in ThumbBrowserEntryBase::releaseNotify (this=0x7fffdc0089c0,
button=1, type=7, 
    bstate=256, x=417, y=19) at /home/cytrinox/src/rawtherapee/rtgui/thumbbrowserentrybase.cc:422
#6  0x00000000006f965f in FileBrowserEntry::releaseNotify (this=0x7fffdc0089c0, button=1,
type=7, 
    bstate=256, x=417, y=19) at /home/cytrinox/src/rawtherapee/rtgui/filebrowserentry.cc:403
#7  0x00000000006eb967 in ThumbBrowserBase::Internal::on_button_release_event (this=0x32e9038,

    event=0x388ba00) at /home/cytrinox/src/rawtherapee/rtgui/thumbbrowserbase.cc:449
#8  0x00007ffff44e6513 in Gtk::Widget_Class::button_release_event_callback(_GtkWidget*,
_GdkEventButton*) () from /usr/lib64/libgtkmm-2.4.so.1
#9  0x00007ffff61f2fc8 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#10 0x00007ffff72a92e2 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#11 0x00007ffff72baabc in ?? () from /usr/lib64/libgobject-2.0.so.0
#12 0x00007ffff72c2396 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#13 0x00007ffff72c2863 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#14 0x00007ffff630ed8f in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#15 0x00007ffff61f1113 in gtk_propagate_event () from /usr/lib64/libgtk-x11-2.0.so.0
#16 0x00007ffff61f14c3 in gtk_main_do_event () from /usr/lib64/libgtk-x11-2.0.so.0
#17 0x00007ffff5e5f32c in ?? () from /usr/lib64/libgdk-x11-2.0.so.0
#18 0x00007ffff6fbf382 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff6fbf6c8 in ?? () from /usr/lib64/libglib-2.0.so.0
#20 0x00007ffff6fbfaba in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#21 0x00007ffff61f04c7 in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
#22 0x00007ffff4479b75 in Gtk::Main::run(Gtk::Window&) () from /usr/lib64/libgtkmm-2.4.so.1
#23 0x000000000081769a in main (argc=1, argv=0x7fffffffdce8)
    at /home/cytrinox/src/rawtherapee/rtgui/main.cc:176

Branch: default
Version: 4.0.9.x
Changeset:  5f6595a5727f
Compiler: gcc 4.5.4
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.2
Build type: Debug
Build flags:   -fopenmp -g
Link flags:    
OpenMP support: ON
MMAP support: ON


```

Reported by `cytrinox` on 2013-02-20 21:57:21

**Comment by Beep6581** [comment]
Still valid.

**Comment by heckflosse** [comment]
Confirmed on Win7/64. Looking...
