### ISSUE TITLE
RT crashes (segfault) with some JPEG images using ciecam

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2402]
Originally reported on Google Code with ID 2419
```
Linux Mint 13 Maya 64 bit

Branch: default
Version: 4.1.15 
Changeset: f87962c15a13
Compiler: gcc 4.6
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.2
Build type: Release
Build flags:   -march=native -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:   -march=native
OpenMP support: ON
MMAP support: ON


RT is crashing with some JPEG files using ciecam:I was able to edit and save such images,but
subsequently RT started to crash while opening that specific folder (even after deleting
the cache),I've traced back the issue to some specific pp3 files using ciecam.

Below is the bt trace from a debug build (it is a patched build that I had already
compiled in Debug version but the issue is apparently the same with a normal non-patched
release build):

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe6058700 (LWP 17933)]
0x0000000000a26ad8 in LUT<float>::operator[] (this=0x7fffe6056e50, 
    index=-nan(0x400000)) at /home/mint13/rawtherapee/rtengine/LUT.h:352
352			T p1 = data[idx];
(gdb) 
#######################################################
#bt full information follows
#######################################################
0  0x0000000000a26ad8 in LUT<float>::operator[] (this=0x7fffe6056e50, 
    index=-nan(0x400000)) at /home/mint13/rawtherapee/rtengine/LUT.h:352
        idx = -2147483648
        diff = -nan(0x400000)
        p1 = -1.57527412e+23
        p2 = 4.59163468e-41
#1  0x0000000000a60807 in rtengine::Chromacurve::Apply (this=0x7fffe6056e40, 
    Cr=@0x7fffe605656c: -nan(0x400000))
    at /home/mint13/rawtherapee/rtengine/curves.h:421
        __PRETTY_FUNCTION__ = "void rtengine::Chromacurve::Apply(float&) const"
#2  0x0000000000a48450 in rtengine::ImProcFunctions::ciecam_02float (
    this=0x7fffe6056b30, ncie=0x7fffc8001a70, adap=4474.66064, begh=0, 
    endh=384, pW=1, pwb=2, lab=0x7fffc80018b0, params=0x7fff98018a28, 
    customColCurve1=..., customColCurve2=..., customColCurve3=..., 
    histLCAM=..., histCCAM=..., CAMBrightCurveJ=..., CAMBrightCurveQ=..., 
    mean=@0x7fffe60578d4: 37.6617546, Iterates=5, scale=6, 
    buffer=0x7fffc8269330, execsharp=false, d=@0x7fffe60578d8: 1, scalecd=16, 
    rtt=0) at /home/mint13/rawtherapee/rtengine/improcfun.cc:1667
        Cc = -nan(0x400000)
        Ccold = -nan(0x400000)
        userColCurve = @0x7fffe6056e40: <incomplete type>
        protect_red = 30
        sk = 1
---Type <return> to continue, or q <return> to quit---

I've attached one of the problematic pp3 files,if you need the image files and corresponding
pp3 files  (it's three of them) I will upload them somewhere and post the link.




```

Reported by `msth67` on 2014-06-11 12:15:10

<hr>
 * *Attachment: [IMG_6052.JPG.pp3](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2419/comment-0/IMG_6052.JPG.pp3)*

**Comment by heckflosse** [comment]
For reference: Should by solved with 721de44
