### ISSUE TITLE
segfault with newwavelet

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#3230]
Hello, something wrong with the wavelet tool in the newwavelet branch. It segfaults when I touch the compression sliders in the Residual image section. A debug build segfaults already when I activate the wavelet tool (so all on top). A backtrace gives this. Version info further down. 

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1ffb700 (LWP 27056)]
0x0000000000e8a73e in rtengine::ImProcFunctions::ip_wavelet ()
    at /home/paul/rtgithubtest345/rtengine/ipwavelet.cc:1191
1191	                    #pragma omp parallel for schedule(dynamic,16) num_threads(wavNestedLevels) if(wavNestedLevels>1)
(gdb) backtrace
#0  0x0000000000e8a73e in rtengine::ImProcFunctions::ip_wavelet ()
    at /home/paul/rtgithubtest345/rtengine/ipwavelet.cc:1191
#1  0x00007ffff35f4cef in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x0000000000e7dd71 in rtengine::ImProcFunctions::ip_wavelet (this=0x41c60c8, lab=0x2b59fa0, 
    dst=0x2b59fa0, mtwo=0, merge_two=0x7fffe1ffa070, ush=0, kall=0, waparams=..., 
    wavCLVCcurve=..., wavRETCcurve=..., wavRETgainCcurve=..., waOpacityCurveRG=..., 
    waOpacityCurveBY=..., waOpacityCurveW=..., waOpacityCurveWL=..., wavclCurve=..., 
    wavcontlutili=false, skip=8, minCD=@0x7fffe1ff910c: 0, maxCD=@0x7fffe1ff9110: 0, 
    mini=@0x7fffe1ff9114: 0, maxi=@0x7fffe1ff9118: 0, Tmean=@0x7fffe1ff911c: 0, 
    Tsigma=@0x7fffe1ff9120: 0, Tmin=@0x7fffe1ff9218: 0, Tmax=@0x7fffe1ff9220: 0)
    at /home/paul/rtgithubtest345/rtengine/ipwavelet.cc:744
#3  0x0000000000d6b99d in rtengine::ImProcCoordinator::updatePreviewImage (this=0x41c6000, todo=3, 
    cropCall=0x0) at /home/paul/rtgithubtest345/rtengine/improccoordinator.cc:909
#4  0x0000000000d6f8db in rtengine::ImProcCoordinator::process (this=0x41c6000)
    at /home/paul/rtgithubtest345/rtengine/improccoordinator.cc:1602
#5  0x0000000000d7395a in sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator>::operator() (
    this=0x32d45b8) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
#6  0x0000000000d73684 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator> >::operator() (this=0x32d45b0)
    at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#7  0x0000000000d731ee in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator>, void>::call_it (rep=0x32d4580) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:103
#8  0x00007ffff6d4255d in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#9  0x00007ffff6fde965 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff31bb6aa in start_thread (arg=0x7fffe1ffb700) at pthread_create.c:333
#11 0x00007ffff2ef0e9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```
```
Branch: newwavelet
Version: 4.2.762
Changeset: d6fcbcf13b901f43db1e346bc18b07a26e1cdccd
Compiler: cc 5.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -w -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:    
OpenMP support: ON
MMAP support: ON
```

**Comment by Desmis** [comment]
hello Paul

I comme back....

I cannot reconstituted, with windows, in Release and Debug mode, all works fine!

@heckflosse   Ingo could you have a look, thank you :)

I have also update Newwavelet with Master and somme iprovments (mutex...)  :)

**Comment by paulmatthijsse** [comment]
Salut Jacques, welcome back!
I confirm that this problem has gone, it was only during a couple of days that this happened. Issue can be closed.

**Comment by adamreichold** [comment]
Closed as indicated by the reporter...
