### ISSUE TITLE
Crash when moving magnify window while "Preview multi-zones" chrominance denosing method is active

### ISSUE THREAD

**Issue by da-phil** [Beep6581/RawTherapee#3379]
```
Branch: master
Version: 4.2.969
Changeset: 3b734e4a7a48917c1c285d9efcfec5170616739a
Compiler: cc 5.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: debug
Build flags:  -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -g
Link flags:    
OpenMP support: ON
MMAP support: ON
```

Recently I worked on some noisy images and played around with different chrominance denoising methods settings. I noticed a fairly reproducible crash when I just selected  "Preview multi-zones" in the chrominance denosing method selection and moved a magnify window around while RT was still occupied calculating the update.

I compiled a debug build and made RT crash several times during gdb sessions.
With several runs I get two different backtraces:

```
...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff807f8700 (LWP 18300)]
0x0000000000da57fd in rtengine::ImProcFunctions::MadRgb (this=0x5254498, DataList=0x7fff5830fc60, datalen=15480) at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2225
2225	        histo[min(65536, abs((int)DataList[i]))]++;
(gdb) bt
#0  0x0000000000da57fd in rtengine::ImProcFunctions::MadRgb (this=0x5254498, DataList=0x7fff5830fc60, datalen=15480) at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2225
#1  0x0000000000da6b8d in rtengine::ImProcFunctions::ShrinkAllAB (this=0x5254498, WaveletCoeffs_L=..., WaveletCoeffs_ab=..., buffer=0x7fff807f7b80, level=0, dir=1, noisevarchrom=0x7fff58043df0, 
    noisevar_ab=0,0199999996, useNoiseCCurve=true, autoch=true, denoiseMethodRgb=true, madL=0x7fff7e7eea50, madaab=0x0, madCalculated=false) at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2784
#2  0x0000000000dc15ce in rtengine::ImProcFunctions::WaveletDenoiseAllAB () at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2646
#3  0x00007ffff36958ac in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#4  0x00007ffff3252184 in start_thread (arg=0x7fff807f8700) at pthread_create.c:312
#5  0x00007ffff2f7f37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

and

```
...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8b7fe700 (LWP 28002)]
0x0000000000da57fd in rtengine::ImProcFunctions::MadRgb (this=0x5319e98, DataList=0x7fff0835c5d0, datalen=15480) at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2225
2225	        histo[min(65536, abs((int)DataList[i]))]++;
(gdb) bt
#0  0x0000000000da57fd in rtengine::ImProcFunctions::MadRgb (this=0x5319e98, DataList=0x7fff0835c5d0, datalen=15480) at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2225
#1  0x0000000000da6b8d in rtengine::ImProcFunctions::ShrinkAllAB (this=0x5319e98, WaveletCoeffs_L=..., WaveletCoeffs_ab=..., buffer=0x7fff8b7f79b0, level=0, dir=2, noisevarchrom=0x7fff08082be0, 
    noisevar_ab=0,0199999996, useNoiseCCurve=true, autoch=true, denoiseMethodRgb=true, madL=0x7fff8b7f7d10, madaab=0x0, madCalculated=false) at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2784
#2  0x0000000000dc15ce in rtengine::ImProcFunctions::WaveletDenoiseAllAB () at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2646
#3  0x00007ffff368ce5f in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#4  0x0000000000da6185 in rtengine::ImProcFunctions::WaveletDenoiseAllAB (this=0x5319e98, WaveletCoeffs_L=..., WaveletCoeffs_ab=..., noisevarchrom=0x7fff08082be0, madL=0x7fff8b7f7d10, noisevar_ab=0, 
    useNoiseCCurve=true, autoch=true, denoiseMethodRgb=true) at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:2627
#5  0x0000000000db0e20 in rtengine::ImProcFunctions::RGB_denoise () at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:1222
#6  0x00007ffff368ce5f in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#7  0x0000000000da470d in rtengine::ImProcFunctions::RGB_denoise (this=0x5319e98, kall=0, src=0x7fff142f5cf0, dst=0x7fff142f5cf0, calclum=0x0, ch_M=0x7fff08002a00, max_r=0x7fff080010a0, max_b=0x7fff08001150, 
    isRAW=true, dnparams=..., expcomp=1,9720645546913147, noiseLCurve=..., noiseCCurve=..., chaut=@0x7fff8b7fc620: 1,26116862e-44, redaut=@0x7fff8b7fc630: 0, blueaut=@0x7fff8b7fc690: 2,34152007, 
    maxredaut=@0x7fff8b7fc6f0: 2,2427783, maxblueaut=@0x7fff8b7fc750: 3,8567786e-34, nresi=@0x7fff8b7fc7c0: 5,64956188e-36, highresi=@0x7fff8b7fc830: 2,59940865e-42)
    at /home/phil/code/rawtherapee-git/rtengine/FTblockDN.cc:853
#8  0x0000000000bcf621 in rtengine::Crop::update (this=0x3cbe360, todo=511) at /home/phil/code/rawtherapee-git/rtengine/dcrop.cc:647
#9  0x0000000000cce4f3 in rtengine::ImProcCoordinator::updatePreviewImage (this=0x5319e00, todo=511, cropCall=0x0) at /home/phil/code/rawtherapee-git/rtengine/improccoordinator.cc:783
#10 0x0000000000cd0f45 in rtengine::ImProcCoordinator::process (this=0x5319e00) at /home/phil/code/rawtherapee-git/rtengine/improccoordinator.cc:1302
#11 0x0000000000cd44ee in sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator>::operator() (this=0x6645178) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
#12 0x0000000000cd4214 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator> >::operator() (this=0x6645170) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:251
#13 0x0000000000cd3de5 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator>, void>::call_it (rep=0x6645140) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:103
#14 0x00007ffff6d4ea4d in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#15 0x00007ffff6fe8f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff3252184 in start_thread (arg=0x7fff8b7fe700) at pthread_create.c:312
#17 0x00007ffff2f7f37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:1
```

**Comment by heckflosse** [comment]
@da-phil Thanks for the good bug report.

**Comment by heckflosse** [comment]
@da-phil I had to revert my commit for a short time to allow an automatic merge of a large pr. I'll let you know when it's in code again.

Ingo

**Comment by da-phil** [comment]
@heckflosse 
great, thanks for the quick bugfix!
