### ISSUE TITLE
Thoughts and findings about limits of 32 bit RawTherapee running on Windows XP32 with 4 GB with Tone mapping and Retinex

### ISSUE THREAD

**Issue by wariag** [Beep6581/RawTherapee#3505]
Hi;

the same settings on regular Bayer RAW files are OK, but there is a crash wit X-trans one.
As a greenhorn I have no idea is it just overkill for my machine or bug.
[log.txt](https://github.com/Beep6581/RawTherapee/files/580652/log.txt)

I have tried the same files on  RT 4.2.1074 from RaweTherapee.com and it is crashing as well.

```
Thread 37 (Thread 13396.0x506c):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90df4a in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x7c809590 in KERNEL32!CreateFileMappingA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#3  0x7c80a115 in WaitForMultipleObjects () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#4  0x64b420d0 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#5  0x64b46a7b in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#6  0x638094c4 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll
No symbol table info available.
#7  0x63809634 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll


No symbol table info available.
#8  0x63809697 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll
No symbol table info available.
#9  0x63807bf8 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll
No symbol table info available.
#10 0x64b44d0d in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#11 0x77c2a3b0 in msvcrt!_endthreadex () from C:\WINDOWS\system32\msvcrt.dll
No symbol table info available.
#12 0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#13 0x00000000 in ?? ()
No symbol table info available.

Thread 36 (Thread 13396.0x5064):
#0  0x687f98ab in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#1  0x687f99c7 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#2  0x666d554e in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglibmm-2.4-1.dll
No symbol table info available.
#3  0x666d1ca4 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglibmm-2.4-1.dll
No symbol table info available.
#4  0x6881987d in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#5  0x64b44d0d in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#6  0x77c2a3b0 in msvcrt!_endthreadex () from C:\WINDOWS\system32\msvcrt.dll
No symbol table info available.
#7  0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#8  0x00000000 in ?? ()
No symbol table info available.

Thread 35 (Thread 13396.0x1754):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90da4a in ntdll!ZwRemoveIoCompletion () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x7c80a7e6 in KERNEL32!GetQueuedCompletionStatus () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#3  0x77e7715c in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#4  0x77e772a0 in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#5  0x77e77328 in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#6  0x77e76ad1 in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#7  0x77e76c97 in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#8  0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#9  0x00000000 in ?? ()
No symbol table info available.

Thread 8 (Thread 13396.0x53a8):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90df4a in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x7c809590 in KERNEL32!CreateFileMappingA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#3  0x68801642 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#4  0x68801988 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#5  0x687f3953 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#6  0x687f3c3a in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#7  0x687f3c78 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#8  0x6881987d in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#9  0x64b44d0d in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#10 0x77c2a3b0 in msvcrt!_endthreadex () from C:\WINDOWS\system32\msvcrt.dll
No symbol table info available.
#11 0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#12 0x00000000 in ?? ()
No symbol table info available.

Thread 7 (Thread 13396.0xaf8):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90df4a in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x7c809590 in KERNEL32!CreateFileMappingA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#3  0x7e3695f9 in USER32!GetLastInputInfo () from C:\WINDOWS\system32\user32.dll
No symbol table info available.
#4  0x7e3696a8 in USER32!MsgWaitForMultipleObjects () from C:\WINDOWS\system32\user32.dll
No symbol table info available.
#5  0x4ebd74b2 in gdiplus!GdipGetVisibleClipBoundsI () from C:\WINDOWS\WinSxS\x86_Microsoft.Windows.GdiPlus_6595b64144ccf1df_1.0.6002.23084_x-ww_f3f35550\GdiPlus.dll
No symbol table info available.
#6  0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#7  0x00000000 in ?? ()
No symbol table info available.

Thread 5 (Thread 13396.0x4c90):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7e3691be in USER32!GetProcessWindowStation () from C:\WINDOWS\system32\user32.dll
No symbol table info available.
#2  0x7e37776b in USER32!GetMessageA () from C:\WINDOWS\system32\user32.dll
No symbol table info available.
#3  0x76b24e31 in WINMM!PlaySoundW () from C:\WINDOWS\system32\winmm.dll
No symbol table info available.
#4  0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#5  0x00000000 in ?? ()
No symbol table info available.

Thread 4 (Thread 13396.0x5078):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90df4a in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x7c809590 in KERNEL32!CreateFileMappingA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#3  0x7c80a115 in WaitForMultipleObjects () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#4  0x72cb312a in midMessage () from C:\WINDOWS\system32\wdmaud.drv
No symbol table info available.
#5  0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#6  0x00000000 in ?? ()
No symbol table info available.

Thread 3 (Thread 13396.0x43cc):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90d21a in ntdll!ZwDelayExecution () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x77e76b99 in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#3  0x77e76b1c in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#4  0x77e76c97 in RPCRT4!I_RpcBCacheFree () from C:\WINDOWS\system32\rpcrt4.dll
No symbol table info available.
#5  0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#6  0x00000000 in ?? ()
No symbol table info available.

Thread 2 (Thread 13396.0x5734):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90df4a in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x7c809590 in KERNEL32!CreateFileMappingA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#3  0x7c80a115 in WaitForMultipleObjects () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#4  0x64b420d0 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#5  0x64b46a7b in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#6  0x638094c4 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll
No symbol table info available.
#7  0x63809634 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll
No symbol table info available.
#8  0x63809697 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll
No symbol table info available.
#9  0x63807bf8 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgomp-1.dll
No symbol table info available.
#10 0x64b44d0d in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libwinpthread-1.dll
No symbol table info available.
#11 0x77c2a3b0 in msvcrt!_endthreadex () from C:\WINDOWS\system32\msvcrt.dll
No symbol table info available.
#12 0x7c80b729 in KERNEL32!GetModuleFileNameA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#13 0x00000000 in ?? ()
No symbol table info available.

Thread 1 (Thread 13396.0x5790):
#0  0x7c90e514 in ntdll!KiFastSystemCallRet () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#1  0x7c90df4a in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\system32\ntdll.dll
No symbol table info available.
#2  0x7c809590 in KERNEL32!CreateFileMappingA () from C:\WINDOWS\system32\kernel32.dll
No symbol table info available.
#3  0x7e3695f9 in USER32!GetLastInputInfo () from C:\WINDOWS\system32\user32.dll
No symbol table info available.
#4  0x688014d7 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#5  0x68801988 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#6  0x687f3953 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#7  0x687f3e93 in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libglib-2.0-0.dll
No symbol table info available.
#8  0x61a4c11f in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgtk-win32-2.0-0.dll
No symbol table info available.
#9  0x050e599c in ?? () from C:\Program Files\RawTherapee-4.2.qqqXPdbg\libgtkmm-2.4-1.dll
No symbol table info available.
#10 0x005b4e4e in main (argc=1, argv=0x5a83350) at D:/msys32/home/user/RawTherapee/rtgui/main.cc:363
        exname = "C:\\Program Files\\RawTherapee-4.2.qqqXPdbg\\rawtherapee.exe", '\000' <repeats 454 times>
        exePath = {static npos = 4294967295, string_ = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x5b0bac0 "C:\\Program Files\\RawTherapee-4.2.qqqXPdbg"}, _M_string_length = 41, {_M_local_buf = ")\000\000\000\000\000\227\005(\000\000\000\000\000\000", _M_allocated_capacity = 41}}}
        exnameU = L<error reading variable>
        consoleOpened = false
        m = <incomplete type>
        icon_path = {static npos = 4294967295, string_ = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x628b918 "C:\\Program Files\\RawTherapee-4.2.qqqXPdbg\\.\\images"}, _M_string_length = 50, {_M_local_buf = "2\000\000\000^\f´\000čó#\000äó#", _M_allocated_capacity = 50}}}
        defaultIconTheme = {pCppObject_ = 0x628cea0}
```

**Comment by Beep6581** [comment]
@wariag please upload the raw file using https://filebin.net/ and in the future surround your console output in code tags (I edited your post and did that, you can edit your post to see how, or look here https://guides.github.com/features/mastering-markdown/ ).

**Comment by wariag** [comment]
RAW and pp3
https://filebin.net/uhxn1nwusm8tnva6

**Comment by heckflosse** [comment]
@wariag Are the Bayer raw files same size (MP) as X-Trans file or smaller? How much RAM is in the XP machine?

**Comment by wariag** [comment]
OK,

so today I have decided to be less narrow-minded and started from scratch. 
I have downloaded several RAW files from cameras with lower/higher pixel count
than mine and tested some with ToneMapping an Retinex.

SO:

my machine has got maximum allowed 4GB of RAM.


With X-Trans sensor:
Tone Mapping works OK on 14 MPx crashes with 16MPx
Retinex does well with 14 and 16 MPx.
RT crashes with "neutral" profile with 24MPx.


With Bayer sensor:
Tone Mapping works OK for files up to 16MPx (bayer), with 20 MPx crashes.
Retinex: works OK for files up to 20MPx, with 24 MPx crashes.
With "neutral" profile RT works up to 24 MPx.

**Comment by gaaned92** [comment]
@wariag Do you use the /3GB boot time switch? see [floating point engine](http://50.87.144.65/~rt/w/index.php?title=The_Floating_Point_Engine)
I think it is mandatory on Windows 32 bits if you want to obtain the maximum from rawtherapee.

**Comment by wariag** [comment]
OK, to be sure I made a clean install. 
It seems that before my system did not use /3GB switch correctly.
The findings above are still correct for 4 GB RAM XP not utilizing /3GB switch.
With correctly used /3GB switch thing gone better:
X-trans 
16 MPx + Tone Mapping =OK
Bayer
20 MPx+ Tone Mapping = OK
24 MPx+ Tone Mapping = crash

I will check these new limits with Retinex and "neutral" profiles on Monday.

**Comment by wariag** [comment]
Update:
With correctly used /3GB switch
X-trans 
16 MPx + Tone Mapping =OK
16 MPx + Tone Mapping = crash
24 MPx + Retinex = OK
Bayer
20 MPx+ Tone Mapping = OK
24 MPx+ Tone Mapping = crash
24 MPx + Retinex = OK
30 MPx  + neutral profile = crash (no crash on load to editor)
36 MPx = crash (even on load to editor)

**Comment by wariag** [comment]
So no issues, just limitations.
Thank You for support.
