### ISSUE TITLE
Segfault when selecting GIMP installation directory in Preferences (Windows)

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3534]
On Win7/64 using master build, when I try to select the GIMP installation directory in Preferences, I get a segfault.

```
(rawtherapee.exe:1328): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed

(rawtherapee.exe:1328): GLib-GObject-WARNING **: ../../glib-2.46.2/gobject/gtype.c:4272: type id '0' is invalid

(rawtherapee.exe:1328): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
Segmentation fault
```

**Comment by heckflosse** [comment]
Here's the bt full:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000619224d3 in ?? () from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
(gdb) bt full
#0  0x00000000619224d3 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#1  0x00000000619226ba in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#2  0x00000000617e9ea1 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#3  0x00000000617c1643 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#4  0x00000000617c75b4 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#5  0x0000000061849acb in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#6  0x0000000063a4611c in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#7  0x0000000063a57002 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#8  0x0000000063a5ec7a in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#9  0x0000000063a5f2d8 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#10 0x000000006195e3ed in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#11 0x0000000061848191 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#12 0x000000006184852b in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#13 0x000000006c378ef2 in ?? ()
   from C:\msys64\mingw64\bin\libgdk-win32-2.0-0.dll
No symbol table info available.
#14 0x00000000685f1d52 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
No symbol table info available.
#15 0x00000000685f1f38 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
No symbol table info available.
#16 0x00000000685f23c3 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
No symbol table info available.
#17 0x00000000617d09a3 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#18 0x0000000000455863 in RTWindow::showPreferences (this=0x81505c0)
    at H:/rt_gimp/rtgui/rtwindow.cc:707
        pref = 0x17abccd0
#19 0x0000000000bcde75 in sigc::bound_mem_functor0<void, RTWindow>::operator()
    (this=0xe6746a8)
    at C:/msys64/mingw64/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
No locals.
#20 0x0000000000bc96ec in sigc::adaptor_functor<sigc::bound_mem_functor0<void, RTWindow> >::operator() (this=0xe6746a0)
    at C:/msys64/mingw64/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
No locals.
#21 0x0000000000b03cf4 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, RTWindow>, void>::call_it (rep=0xe674670)
    at C:/msys64/mingw64/include/sigc++-2.0/sigc++/functors/slot.h:108
        typed_rep = 0xe674670
#22 0x00000000664d99bc in ?? () from C:\msys64\mingw64\bin\libglibmm-2.4-1.dll
No symbol table info available.
#23 0x0000000063a4611c in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#24 0x0000000063a572a9 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#25 0x0000000063a5f068 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#26 0x0000000063a5f2d8 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#27 0x00000000617a39b5 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#28 0x0000000063a46357 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#29 0x0000000063a5edcd in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#30 0x0000000063a5f2d8 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#31 0x00000000617a3739 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#32 0x0000000061849acb in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#33 0x0000000063a4611c in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#34 0x0000000063a575d5 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#35 0x0000000063a5ec7a in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#36 0x0000000063a5f2d8 in ?? ()
   from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
No symbol table info available.
#37 0x000000006195e3ed in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#38 0x0000000061848191 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#39 0x000000006184852b in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#40 0x000000006c378ef2 in ?? ()
   from C:\msys64\mingw64\bin\libgdk-win32-2.0-0.dll
No symbol table info available.
#41 0x00000000685f1d52 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
No symbol table info available.
#42 0x00000000685f1f38 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
No symbol table info available.
#43 0x00000000685f23c3 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
No symbol table info available.
#44 0x00000000618475d0 in ?? ()
   from C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#45 0x00000000056b61f0 in ?? () from C:\msys64\mingw64\bin\libgtkmm-2.4-1.dll
No symbol table info available.
#46 0x00000000005d7f07 in main (argc=1, argv=0x6ea2760)
    at H:/rt_gimp/rtgui/main.cc:363
        exname = "H:\\rt_gimp\\build\\Debug\\rawtherapee.exe", '\000' <repeats 473 times>
        exePath = {static npos = 18446744073709551615, string_ = {
            static npos = <optimized out>,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
              _M_p = 0x74e1270 "H:\\rt_gimp\\build\\Debug"},
            _M_string_length = 22, {
              _M_local_buf = "\036\000\000\000\000\000\000\000\000\000T\005\000\000\000", _M_allocated_capacity = 30}}}
        exnameU = L"H:\\rt_gimp\\build\\Debug\\rawtherapee.exe", '\000' <repeats 473 times>
        consoleOpened = false
        m = <incomplete type>
        icon_path = {static npos = 18446744073709551615, string_ = {
            static npos = <optimized out>,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
              _M_p = 0x81434a0 "H:\\rt_gimp\\build\\Debug\\.\\images"},
            _M_string_length = 31, {
              _M_local_buf = "\037\000\000\000\000\000\000\000\060@\000\000\000\000\000", _M_allocated_capacity = 31}}}
        defaultIconTheme = {pCppObject_ = 0x814e4e0}
        rtWindow = 0x81505c0
(gdb)
```

**Comment by heckflosse** [comment]
I checked gtk3-bugfix branch too. There it works fine.

**Comment by heckflosse** [comment]
Addition: It crashes only when the current directory is 'none'

**Comment by heckflosse** [comment]
Suggested fix:

```
diff --git a/rtgui/preferences.cc b/rtgui/preferences.cc
index 748531f..44f868a 100644
--- a/rtgui/preferences.cc
+++ b/rtgui/preferences.cc
@@ -1665,10 +1665,16 @@ void Preferences::fillPreferences ()
 
     if (Glib::file_test (moptions.gimpDir, Glib::FILE_TEST_IS_DIR)) {
         gimpDir->set_current_folder (moptions.gimpDir);
+    } else {
+        const gchar* sysRoot = g_getenv("SystemRoot");  // Returns e.g. "c:\Windows"
+        gimpDir->set_current_folder (sysRoot);
     }
 
     if (Glib::file_test (moptions.psDir, Glib::FILE_TEST_IS_DIR)) {
         psDir->set_current_folder (moptions.psDir);
+    } else {
+        const gchar* sysRoot = g_getenv("SystemRoot");  // Returns e.g. "c:\Windows"
+        psDir->set_current_folder (sysRoot);
     }
 
 #elif defined __APPLE__

```

**Comment by heckflosse** [comment]
This one is enough to fix the crash:

```
diff --git a/rtgui/preferences.cc b/rtgui/preferences.cc
index 748531f..aec988d 100644
--- a/rtgui/preferences.cc
+++ b/rtgui/preferences.cc
@@ -1665,10 +1665,14 @@ void Preferences::fillPreferences ()
 
     if (Glib::file_test (moptions.gimpDir, Glib::FILE_TEST_IS_DIR)) {
         gimpDir->set_current_folder (moptions.gimpDir);
+    } else {
+        gimpDir->set_current_folder ("");
     }
 
     if (Glib::file_test (moptions.psDir, Glib::FILE_TEST_IS_DIR)) {
         psDir->set_current_folder (moptions.psDir);
+    } else {
+        psDir->set_current_folder ("");
     }
 
 #elif defined __APPLE__

```
