### ISSUE TITLE
Crash opening tiff - after save of earlier file.

### ISSUE THREAD

**Issue by jtappin** [Beep6581/RawTherapee#3593]
There is a problem where opening a large(ish) greyscale or RGB 16-bit tiff can cause a crash (sometimes with a double free error).
```
*** Error in `./rtgui/rawtherapee': double free or corruption (!prev): 0x00000000044e8dc0 ***
**
Gdk:ERROR:gdkregion-generic.c:1110:miUnionNonO: assertion failed: (y1 < y2)
Aborted (core dumped)
```
This is with a git checkout of the master branch from yesterday. 
It appears that the problem is only triggered when, a previous file has been opened, and then exported with a scaling change.
The double free message only seems to appear for greyscale images.
The threshold in size seems to be around the 10MP mark, I get it consistently with 20MP images but not with 8MP.

Not sure how to get a more detailed traceback, as this was on a build with `-DCMAKE_BUILD_TYPE=Debug` on the cmake configuration stage.

**Comment by Beep6581** [comment]
Steps to reproduce?
http://rawpedia.pixls.us/index.php/How_to_write_useful_bug_reports

**Comment by jtappin** [comment]
1) Launch Rawtherapee
2) Open a 16-bit tiff file, and process to taste,
3) Save to jpeg with a reduced size
4) Open another 16-bit tiff from the browser or the top bar -- there is a good chance of a crash.

It is at least to some extent a heisenbug -- greyscales seem to be more consistently problematic than RGB.

**Comment by jtappin** [comment]
I should have added I'm running on Linux (up-to-date Manjaro).

**Comment by Beep6581** [comment]
I've been getting crashes related to perhaps this since forever. The key seems to be to save the image to the same folder as the one you're currently in (your steps don't mention where to save, did you mean to the current folder?). I saved the TIFF to /tmp. When I open one of these and save a new JPG also to /tmp. The filmstrip doesn't update with the new image. I go to the file browser and click on /tmp, then the new images appear. If I open a few of them RT will crash.

```
Program received signal SIGABRT, Aborted.
0x00007ffff140870b in raise () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff140870b in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff1409cd1 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff144b6ec in ?? () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff1451567 in ?? () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff1452e4a in ?? () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007ffff1455b45 in calloc () from /lib64/libc.so.6
No symbol table info available.
#6  0x00007ffff6fa4a71 in g_malloc0 () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ffff6f9d1a7 in g_source_new () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#8  0x00007ffff6fa0422 in g_idle_source_new () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#9  0x00007ffff6fa045e in g_idle_add_full () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#10 0x00007ffff63216c7 in ?? () from /usr/lib64/libgtk-3.so.0
No symbol table info available.
#11 0x00007ffff7278e05 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#12 0x00007ffff728aa01 in ?? () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#13 0x00007ffff72932b6 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007ffff72934e2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#15 0x00007ffff61ed465 in gtk_list_store_remove () from /usr/lib64/libgtk-3.so.0
No symbol table info available.
#16 0x00007ffff61edb67 in gtk_list_store_clear () from /usr/lib64/libgtk-3.so.0
No symbol table info available.
#17 0x00005555559cf751 in History::initHistory (this=0x55555948e490) at /home/morgan/programs/code-rawtherapee/rtgui/history.cc:160
        selBlocker = {connection = 0x55555948e5d0, wasBlocked = true}
#18 0x00005555559d3a88 in History::procParamsChanged (this=0x55555948e490, params=0x55555c9d9d48, ev=rtengine::EvPhotoLoaded, descr=..., paramsEdited=0x0) at /home/morgan/programs/code-rawtherapee/rtgui/history.cc:238
        iter = {<Gtk::TreeIterBase> = {gobject_ = {stamp = 1, user_data = 0x2, user_data2 = 0x7fffffffaac0, user_data3 = 0x7ffff1412851}}, model_ = 0x7fffffffa6d0, is_end_ = false}
        text = {static npos = 18446744073709551615, string_ = ""}
        selection = {pCppObject_ = 0x0}
        size = <optimized out>
        row = {<Gtk::TreeIter> = {<Gtk::TreeIterBase> = {gobject_ = {stamp = 5, user_data = 0x7fffffffa6d0, user_data2 = 0x18000000000000, user_data3 = 0x7fffffffa6e0}}, model_ = 0x1, is_end_ = false}, <No data fields>}
#19 0x0000555555ad2d0c in ToolPanelCoordinator::profileChange (this=<optimized out>, nparams=<optimized out>, event=rtengine::EvPhotoLoaded, descr=..., paramsEdited=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/toolpanelcoord.cc:456
        paramcListener = 0x55555948e4b8
        __for_range = <optimized out>
        fh = 3328
        tr = <optimized out>
        params = 0x55555c9d9d48
        mergedParams = <optimized out>
        fw = 5000
        filterRawRefresh = false
#20 0x0000555555a94cab in ProfilePanel::initProfile (this=0x55555bb31780, profileFullPath=..., lastSaved=lastSaved@entry=0x55555e232000) at /home/morgan/programs/code-rawtherapee/rtgui/profilepanel.cc:766
        pse = 0x5555564f6bb0
        defprofile = 0x555556285a10
        ccPrevState = false
        lasSavedEntry = {<Gtk::TreeIterBase> = {gobject_ = {stamp = -1676114057, user_data = 0x55555da5a4d0, user_data2 = 0x0, user_data3 = 0x0}}, model_ = 0x55555dcd2c08, is_end_ = false}
#21 0x0000555555880fab in EditorPanel::open (this=0x5555597f2050, tmb=0x7fffa8004000, isrc=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/editorpanel.cc:866
        is = 0x7fff30001500
        ldprof = 0x55555e232000
        defProf = {static npos = 18446744073709551615, string_ = "Neutral"}
#22 0x00005555558764b6 in FilePanel::imageLoaded (this=0x555556e16d80, thm=0x7fffa8004000, pc=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/filepanel.cc:288
        pl = 0x555558e65e80
#23 0x00005555558779df in sigc::internal::signal_emit0<bool, sigc::nil>::emit (impl=0x55555e2617a0) at /usr/include/sigc++-2.0/sigc++/signal.h:701
---Type <return> to continue, or q <return> to quit---
        it = {<sigc::functor_base> = {<No data fields>}, rep_ = , blocked_ = false}
        r_ = false
#24 sigc::signal0<bool, sigc::nil>::emit (this=0x7fff30005950) at /usr/include/sigc++-2.0/sigc++/signal.h:2701
No locals.
#25 ProgressConnector<rtengine::InitialImage*>::emitEndSignalUI (data=0x7fff30005950) at /home/morgan/programs/code-rawtherapee/rtgui/progressconnector.h:78
        opEnd = 0x7fff30005950
        r = <optimized out>
#26 0x00007ffff6f9f4ed in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#27 0x00007ffff6f9f888 in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#28 0x00007ffff6f9fba2 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#29 0x00007ffff61f0b05 in gtk_main () from /usr/lib64/libgtk-3.so.0
No symbol table info available.
#30 0x00007ffff47674f1 in Gtk::Main::run(Gtk::Window&) () from /usr/lib64/libgtkmm-3.0.so.1
No symbol table info available.
#31 0x0000555555800a53 in main (argc=1, argv=0x7fffffffd738) at /home/morgan/programs/code-rawtherapee/rtgui/main.cc:381
        exname = "/home/morgan/rt_gtk3/rawtherapee", '\000' <repeats 479 times>
        exePath = {static npos = 18446744073709551615, string_ = "/home/morgan/rt_gtk3"}
        m = <incomplete type>
        icon_path = {static npos = 18446744073709551615, string_ = "/home/morgan/rt_gtk3/./images"}
        screen = {pCppObject_ = 0x555556c99830}
        rtWindow = 0x555556401110
        defaultIconTheme = {pCppObject_ = 0x555556c99540}
```

**Comment by jtappin** [comment]
I usually save to the directory containing the original file, [actually I'd like to be able to set that as the default behaviour -- rather than the directory in which I last saved something -- but that's a separate issue].

I have never seen the problem with camera raw files, and I don't make a habit of editing jpegs with RT.

I'd say it has all the feel of a buffer overrun. 

If it's any use, here is a gdb "where" output from a crash:
```
Gdk:ERROR:gdkregion-generic.c:1123:miUnionNonO: assertion failed: (pReg->numRects<=pReg->size)
**
Gdk:ERROR:gdkregion-generic.c:1123:miUnionNonO: assertion failed: (pReg->numRects<=pReg->size)

Thread 1 "rawtherapee" received signal SIGABRT, Aborted.
0x00007ffff2db704f in raise () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007ffff2db704f in raise () at /usr/lib/libc.so.6
#1  0x00007ffff2db847a in abort () at /usr/lib/libc.so.6
#2  0x00007ffff6fac2a5 in g_assertion_message () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff6fac33a in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff61ee9f5 in  () at /usr/lib/libgdk-x11-2.0.so.0
#5  0x00007ffff61efb34 in  () at /usr/lib/libgdk-x11-2.0.so.0
#6  0x00007ffff61f0379 in gdk_region_union () at /usr/lib/libgdk-x11-2.0.so.0
#7  0x00007ffff61fad80 in  () at /usr/lib/libgdk-x11-2.0.so.0
#8  0x00007ffff66ba2ed in  () at /usr/lib/libgtk-x11-2.0.so.0
#9  0x00007ffff66bffcc in  () at /usr/lib/libgtk-x11-2.0.so.0
#10 0x00007ffff66c0058 in gtk_widget_queue_resize () at /usr/lib/libgtk-x11-2.0.so.0
#11 0x00007ffff6593af0 in  () at /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff6594aa9 in gtk_label_set_text () at /usr/lib/libgtk-x11-2.0.so.0
#13 0x000000000079b3fc in ZoomPanel::refreshZoomLabel() (this=0x27b9900)
    at /data/software/AUR/rawtherapee-git/src/rawtherapee/rtgui/zoompanel.cc:138
#14 0x0000000000538420 in CropWindow::changeZoom(int, bool, int, int) (this=0x3b4c7b0, zoom=<optimized out>, notify=<optimized out>, centerx=<optimized out>, centery=<optimized out>)
    at /data/software/AUR/rawtherapee-git/src/rawtherapee/rtgui/cropwindow.cc:2112
#15 0x0000000000538b59 in CropWindow::zoomFit() (this=0x3b4c7b0)
    at /data/software/AUR/rawtherapee-git/src/rawtherapee/rtgui/cropwindow.cc:2013
#16 0x00000000006c1950 in ImageArea::initialImageArrived(CropWindow*) (this=0x27b9720, cw=<optimized out>)
    at /data/software/AUR/rawtherapee-git/src/rawtherapee/rtgui/imagearea.cc:647
#17 0x0000000000537dc0 in CropWindow::initialImageArrived() (this=0x3b4c7b0)
    at /data/software/AUR/rawtherapee-git/src/rawtherapee/rtgui/cropwindow.cc:2487
#18 0x000000000057dd25 in EditorPanel::open(Thumbnail*, rtengine::InitialImage*) (this=0x1ebcee0, tmb=0x7fffc8015500, isrc=<optimized out>) at /data/software/AUR/rawtherapee-git/src/rawtherapee/rtgui/editorpanel.cc:861
#19 0x00000000005788af in FilePanel::imageLoaded(Thumbnail*, ProgressConnector<rtengine::InitialImage*>*) (this=0x132ad10, thm=0x7fffc8015500, pc=<optimized out>) at /data/software/AUR/rawtherapee-git/src/rawtherapee/rtgui/filepanel.cc:276
---Type <return> to continue, or q <return> to quit---
```
