### ISSUE TITLE
Crashes with locallab_dev (starting RT, adding to queue, ..)

### ISSUE THREAD

**Issue by Blizzara** [Beep6581/RawTherapee#3835]
Hi,

During the week-end I got a couple of crashes when using RT, some right after opening, some related to adding/canceling items from Queue and one while not doing anything. I was using the locallab_dev branch, but not any locallab-features, and at that time the branch was up-to-date with dev. The crashes seemed to be quite random, so sadly I cannot give any steps to reproduce.. For example, the opening of RT failed (IIRC) twice in a row but then the third time succeeded, and then at some point later it again failed.

Version info:
```
Version: 5.0-r1-gtk3-517-geb8a1c9
Branch: locallab_dev
Commit: eb8a1c9
Commit date: 2017-04-15
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: relwithdebinfo
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O2 -g -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

And some stack traces below. Please let me know if I can be of any further assistance with this, and thanks for the great job you are all doing with RT! :)

-Arttu

Crashes while opening:
```
Thread 1 "rawtherapee" received signal SIGABRT, Aborted.
0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff29f402a in __GI_abort () at abort.c:89
#2  0x00007ffff2a347ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff2b4d2e0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff2a40e58 in malloc_printerr (ar_ptr=<optimized out>, ptr=0x7ffff79bad00, str=0x7ffff2b4a1c6 "realloc(): invalid pointer", action=3) at malloc.c:5004
#4  __GI___libc_realloc (oldmem=0x7ffff79bad00, bytes=<optimized out>) at malloc.c:3011
#5  0x00007ffff68a27d8 in g_realloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff71ff209 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff71ff43a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff71fe22d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff7298bb1 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff6b97317 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6b7931b in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6b7b1b5 in g_object_new_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6b7b521 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff72eb143 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff72ee025 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff6b73fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6b85fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6b8ed5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff73a4526 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007fffeffd0237 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#22 0x00007fffefff5457 in g_simple_async_result_complete () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#23 0x00007fffefff54b9 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#24 0x00007ffff689d04a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff689d3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff689d712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff72a3395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff55fcfcf in Gtk::Main::run(Gtk::Window&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#29 0x0000000000517378 in main (argc=1, argv=0x7fffffffdcd8) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/main.cc:389
```
```
Thread 31 "pool" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd2277700 (LWP 25792)]
0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff29f402a in __GI_abort () at abort.c:89
#2  0x00007ffff2a347ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff2b4d2e0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff2a3ce0a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7ffff2b4a0b2 "free(): invalid pointer", action=3) at malloc.c:5004
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3865
#5  0x00007ffff2a4098c in __GI___libc_free (mem=<optimized out>) at malloc.c:2966
#6  0x00007ffff71fd71b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff6b78d9a in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7347166 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff73f1319 in gtk_widget_get_style_context () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff73f1a98 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff73f1e1f in gtk_widget_realize () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff73f1ff8 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff7262a10 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff71eb8af in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff6b741d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff6b8e9a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff73f1fb0 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff73f4c57 in gtk_widget_set_parent () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff72d9af8 in gtk_notebook_set_tab_label () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x000000000065804d in FileCatalog::_refreshProgressBar (this=this@entry=0x3c00130) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filecatalog.cc:702
#22 0x000000000065a812 in FileCatalog::previewReady (this=0x3c00130, dir_id=<optimized out>, fdn=0x7fffcc02ebe0)
        at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filecatalog.cc:778
#23 0x00000000007d9a47 in PreviewLoader::Impl::processNextJob (this=0x76cefa0) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/previewloader.cc:134
#24 0x00007ffff5c5b5c2 in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#25 0x00007ffff68c454e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff68c3bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff2d8d6ba in start_thread (arg=0x7fffd2277700) at pthread_create.c:333
#28 0x00007ffff2ac382d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
```
Thread 28 "pool" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffaedfc700 (LWP 29740)]
0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff29f402a in __GI_abort () at abort.c:89
#2  0x00007ffff2a347ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff2b4d2e0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff2a40e58 in malloc_printerr (ar_ptr=<optimized out>, ptr=0x7ffff79bad00, str=0x7ffff2b4a1c6 "realloc(): invalid pointer", action=3) at malloc.c:5004
#4  __GI___libc_realloc (oldmem=0x7ffff79bad00, bytes=<optimized out>) at malloc.c:3011
#5  0x00007ffff68a27d8 in g_realloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff71ff209 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff71ff43a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff71fe22d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff72dc03f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff6b97317 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6b7931b in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6b7ac01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff5c5853d in Glib::Object::Object(Glib::ConstructParams const&) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#14 0x00007ffff568d966 in Gtk::Object::Object(Glib::ConstructParams const&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#15 0x00007ffff5669502 in Gtk::Widget::Widget(Glib::ConstructParams const&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#16 0x00007ffff55c8a75 in Gtk::Container::Container(Glib::ConstructParams const&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#17 0x00007ffff55e97c0 in Gtk::Grid::Grid() () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#18 0x0000000000657cb9 in FileCatalog::_refreshProgressBar (this=this@entry=0x3c0f000) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filecatalog.cc:676
#19 0x000000000065a812 in FileCatalog::previewReady (this=0x3c0f000, dir_id=<optimized out>, fdn=0x7fffa0030880)
        at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filecatalog.cc:778
#20 0x00000000007d9a47 in PreviewLoader::Impl::processNextJob (this=0x219a620) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/previewloader.cc:134
#21 0x00007ffff5c5b5c2 in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#22 0x00007ffff68c454e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff68c3bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff2d8d6ba in start_thread (arg=0x7fffaedfc700) at pthread_create.c:333
#25 0x00007ffff2ac382d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Adding items to Queue:
```
Thread 1 "rawtherapee" received signal SIGSEGV, Segmentation fault.
0x000000000052c6b1 in BatchQueue::saveBatchQueue (this=this@entry=0x3eb0400)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:245
    245                  << entry->job->fastPipeline() << '|'
    (gdb) bt
#0  0x000000000052c6b1 in BatchQueue::saveBatchQueue (
        this=this@entry=0x3eb0400)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:245
#1  0x000000000052e0b6 in BatchQueue::addEntries (this=0x3eb0400, entries=..., 
        head=head@entry=false, save=save@entry=true)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:207
#2  0x00000000005409b8 in BatchQueuePanel::addBatchQueueJobs (this=0x3eab960, 
        entries=..., head=head@entry=false)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueuepanel.cc:311
#3  0x00000000008193bf in RTWindow::addBatchQueueJobs (this=0x1112ed0, 
        entries=...)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/rtwindow.cc:573
#4  0x0000000000676a85 in FilePanel::addBatchQueueJobs (this=<optimized out>, 
        entries=...)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filepanel.cc:349
#5  0x00000000006713e6 in FileCatalog::developRequested (this=0x3c02000, 
        tbe=std::vector of length 482, capacity 482 = {...}, fastmode=false)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filecatalog.cc:1215
#6  0x000000000064f6fb in FileBrowser::menuItemActivated (this=0x3c02900, 
        m=0x3c0a370)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filebrowser.cc:768
#7  0x00007ffff5c5a1f8 in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
    ---Type <return> to continue, or q <return> to quit---
#8  0x00007ffff6b73fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff6b86264 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6b8ed5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff73e50fe in gtk_widget_activate () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff72c2766 in gtk_menu_shell_activate_item () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff72c2a94 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff72a509a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff6b741d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6b8e4b8 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff73e2c5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff72a23be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff72a41bc in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff6e11d92 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#23 0x00007ffff689d197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff689d3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff689d712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff72a3395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff55fcfcf in Gtk::Main::run(Gtk::Window&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#28 0x0000000000517378 in main (argc=1, argv=0x7fffffffdcd8) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/main.cc:389
```
```
Thread 1 "rawtherapee" received signal SIGSEGV, Segmentation fault.
0x0000000004364660 in ?? ()
(gdb) bt
#0  0x0000000004364660 in ?? ()
#1  0x000000000052c6b4 in BatchQueue::saveBatchQueue (this=this@entry=0x3eaf640) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:245
#2  0x000000000052e0b6 in BatchQueue::addEntries (this=0x3eaf640, entries=..., head=head@entry=false, save=save@entry=true)
    at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:207
#3  0x00000000005409b8 in BatchQueuePanel::addBatchQueueJobs (this=0x3eaa680, entries=..., head=head@entry=false)
        at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueuepanel.cc:311
#4  0x00000000008193bf in RTWindow::addBatchQueueJobs (this=0x111acb0, entries=...) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/rtwindow.cc:573
#5  0x0000000000676a85 in FilePanel::addBatchQueueJobs (this=<optimized out>, entries=...) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filepanel.cc:349
#6  0x00000000006713e6 in FileCatalog::developRequested (this=0x3c00340, tbe=std::vector of length 109, capacity 109 = {...}, fastmode=false)
            at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filecatalog.cc:1215
#7  0x000000000064f6fb in FileBrowser::menuItemActivated (this=0x3c00c40, m=0x3c09880) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/filebrowser.cc:768
#8  0x00007ffff5c5a1f8 in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#9  0x00007ffff6b73fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6b86264 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6b8ed5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff73e50fe in gtk_widget_activate () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff72c2766 in gtk_menu_shell_activate_item () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff72c2a94 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff72a509a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff6b741d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6b8e4b8 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff73e2c5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff72a23be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff72a41bc in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff6e11d92 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#24 0x00007ffff689d197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff689d3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff689d712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff72a3395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff55fcfcf in Gtk::Main::run(Gtk::Window&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#29 0x0000000000517378 in main (argc=1, argv=0x7fffffffdcd8) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/main.cc:389
```

Cancelling items from queue:
```
Thread 1 "rawtherapee" received signal SIGSEGV, Segmentation fault.
0x00000000064eb7f0 in ?? ()
(gdb) bt
#0  0x00000000064eb7f0 in ?? ()
#1  0x000000000052c6b4 in BatchQueue::saveBatchQueue (this=this@entry=0x3ea4000) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:245
#2  0x000000000052db7b in BatchQueue::cancelItems (this=0x3ea4000, items=...) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:433
#3  0x00007ffff5c5a1f8 in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#4  0x00007ffff6b73fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff6b86264 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff6b8ed5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff73e50fe in gtk_widget_activate () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff72c2766 in gtk_menu_shell_activate_item () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff72c2a94 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff72a509a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff6b741d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6b8e4b8 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff6b8f08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff73e2c5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff72a23be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff72a41bc in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff6e11d92 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#19 0x00007ffff689d197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff689d3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff689d712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff72a3395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff55fcfcf in Gtk::Main::run(Gtk::Window&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#24 0x0000000000517378 in main (argc=1, argv=0x7fffffffdcd8) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/main.cc:389
```

Not doing anything (Queue ongoing):
```
Thread 1 "rawtherapee" received signal SIGABRT, Aborted.
0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff29f2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff29f402a in __GI_abort () at abort.c:89
#2  0x00007ffff377384d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff37716b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff3771701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff3771919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff5c418b7 in Glib::FileError::throw_func(_GError*) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#7  0x00007ffff5c53d12 in Glib::Error::throw_exception(_GError*) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#8  0x00007ffff4e636f4 in Gdk::Pixbuf::create_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libgdkmm-3.0.so.1
#9  0x000000000081831b in RTImage::changeImage (this=this@entry=0xcf67d00, imageName=...) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/rtimage.cc:56
#10 0x0000000000818568 in RTImage::RTImage (this=0xcf67d00, fileName=..., rtlFileName=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
       at /home/blizzara/Dropbox/git/RawTherapee/rtgui/rtimage.cc:45
#11 0x000000000053fdd1 in BatchQueuePanel::updateTab (this=this@entry=0x3ea6fe0, qsize=89, forceOrientation=forceOrientation@entry=0)
           at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueuepanel.cc:223
#12 0x000000000054086d in BatchQueuePanel::stopBatchProc (this=this@entry=0x3ea6fe0) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueuepanel.cc:305
#13 0x00000000005453e0 in BatchQueuePanel::queueSizeChanged (this=0x3ea6fe0, qsize=<optimized out>, queueEmptied=<optimized out>, queueError=<optimized out>, 
               queueErrorMessage=...) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueuepanel.cc:261
#14 0x000000000052be18 in bqnotifylistenerUI (data=0x7ffd10055b30) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/batchqueue.cc:925
#15 0x00000000006a2c58 in IdleRegister::<lambda(gpointer)>::operator() (__closure=0x0, data=0x7ffd1012e860)
                   at /home/blizzara/Dropbox/git/RawTherapee/rtgui/guiutils.cc:57
#16 IdleRegister::<lambda(gpointer)>::_FUN(gpointer) () at /home/blizzara/Dropbox/git/RawTherapee/rtgui/guiutils.cc:67
#17 0x00007ffff6dde3c8 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#18 0x00007ffff689d04a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff689d3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff689d712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff72a3395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff55fcfcf in Gtk::Main::run(Gtk::Window&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#23 0x0000000000517378 in main (argc=1, argv=0x7fffffffdcd8) at /home/blizzara/Dropbox/git/RawTherapee/rtgui/main.cc:389
```

System:
```
Linux 4.4.0-74-generic #95-Ubuntu SMP Wed Apr 12 09:50:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Description:	Ubuntu 16.04.2 LTS
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
24GB RAM
```

**Comment by Blizzara** [comment]
I haven't gotten any crashes so far with the released version of 5.1, so I'm closing this. Thanks for the great work you're doing!
