### ISSUE TITLE
Crash in guiutils on opening folder in File Browser

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3849]
Tested using 5.0-r1-gtk3-474-g d8e0207b 
I simply open two or three folders in the File Browser.
```
(rawtherapee:7989): GLib-CRITICAL **: Source ID 3159 was not found when attempting to remove it
*** Error in `/home/morgan/programs/code-rawtherapee/build/debug/rawtherapee': double free or corruption (fasttop): 0x00007fff8c025330 ***
```
```
Thread 1 "rawtherapee" received signal SIGABRT, Aborted.
0x00007ffff13e332b in raise () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff13e332b in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff13e49a1 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff14229dc in ?? () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff14289ff in ?? () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff142926e in ?? () from /lib64/libc.so.6
No symbol table info available.
#5  0x0000555555d18e2b in IdleRegister::destroy (this=0x7fff78003b30) at /home/morgan/programs/code-rawtherapee/rtgui/guiutils.cc:92
        w = 0x7fff8c025330
        id = {first = 0x7fff8c025330, second = 3159}
        __for_range = std::map with 1 elements = {[0x7fff8c025330] = 3159}
        __for_begin = {first = , second = 3159}
        __for_end = {first = , second = 2013274944}
#6  0x0000555555d18b16 in IdleRegister::~IdleRegister (this=0x7fff78003b30, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/guiutils.cc:43
No locals.
#7  0x0000555555caee47 in FileBrowserEntry::~FileBrowserEntry (this=0x7fff78003970, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/filebrowserentry.cc:68
No locals.
#8  0x0000555555caeeec in FileBrowserEntry::~FileBrowserEntry (this=0x7fff78003970, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/filebrowserentry.cc:86
No locals.
#9  0x0000555555c9363f in FileBrowser::close (this=0x55555a56f800) at /home/morgan/programs/code-rawtherapee/rtgui/filebrowser.cc:680
        i = 2
        l = {<rtengine::NonCopyable> = {<No data fields>}, mutex = @0x55555a56f970, locked = true}
#10 0x0000555555cc479e in FileCatalog::closeDir (this=0x55555a56e6d0) at /home/morgan/programs/code-rawtherapee/rtgui/filecatalog.cc:537
No locals.
#11 0x0000555555cc4f9c in FileCatalog::dirSelected (this=0x55555a56e6d0, dirname=..., openfile=...) at /home/morgan/programs/code-rawtherapee/rtgui/filecatalog.cc:601
        dir = {pCppObject_ = 0x55555d7f2b30}
#12 0x0000555555ce7981 in sigc::bound_mem_functor2<void, FileCatalog, Glib::ustring const&, Glib::ustring const&>::operator() (this=0x55555a6db838, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:2143
No locals.
#13 0x0000555555ce5cd3 in sigc::adaptor_functor<sigc::bound_mem_functor2<void, FileCatalog, Glib::ustring const&, Glib::ustring const&> >::operator()<Glib::ustring const&, Glib::ustring const&> (this=0x55555a6db830, _A_arg1=..., _A_arg2=...)
    at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:108
No locals.
#14 0x0000555555ce3dbc in sigc::internal::slot_call<sigc::bound_mem_functor2<void, FileCatalog, Glib::ustring const&, Glib::ustring const&>, void, Glib::ustring const&, Glib::ustring const&>::call_it (rep=0x55555a6db800, a_#0=..., a_#1=...)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:429
        typed_rep = 0x55555a6db800
#15 0x0000555555bed3fd in sigc::internal::signal_emit2<void, Glib::ustring const&, Glib::ustring const&, sigc::nil>::emit (impl=0x55555a6db7e0, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/signal.h:1296
        slot = @0x55555a6dd0a0: {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6db800, blocked_ = false}
        __for_range = @0x7fffffffb7a0: {slots_ = std::list = {[0] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6db800, blocked_ = false}, [1] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6dd0c0, blocked_ = false}, 
            [2] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6dd1a0, blocked_ = false}, [3] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6dd280, blocked_ = false}, [4] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x0, 
              blocked_ = false}}, placeholder = {<sigc::functor_base> = {<No data fields>}, rep_ = , blocked_ = false}}
        __for_begin = {<sigc::functor_base> = {<No data fields>}, rep_ = , blocked_ = false}
        __for_end = {<sigc::functor_base> = {<No data fields>}, rep_ = , blocked_ = false}
        exec = {sig_ = 0x55555a6db7e0}
        slots = {slots_ = std::list = {[0] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6db800, blocked_ = false}, [1] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6dd0c0, blocked_ = false}, 
            [2] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6dd1a0, blocked_ = false}, [3] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x55555a6dd280, blocked_ = false}, [4] = {<sigc::functor_base> = {<No data fields>}, rep_ = 0x0, 
              blocked_ = false}}, placeholder = {<sigc::functor_base> = {<No data fields>}, rep_ = , blocked_ = false}}
#16 0x0000555555bec329 in sigc::signal2<void, Glib::ustring const&, Glib::ustring const&, sigc::nil>::emit (this=0x555557ba7d60, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/signal.h:3104
No locals.
#17 0x0000555555beaead in sigc::signal2<void, Glib::ustring const&, Glib::ustring const&, sigc::nil>::operator() (this=0x555557ba7d60, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/signal.h:3120
No locals.
#18 0x0000555555be5e4d in DirBrowser::row_activated (this=0x555557ba7c00, path=..., column=0x555557ba7ca0) at /home/morgan/programs/code-rawtherapee/rtgui/dirbrowser.cc:390
        dname = {static npos = 18446744073709551615, string_ = "/home/morgan/photos/2017-04-23 pizzeria"}
#19 0x0000555555bef028 in sigc::bound_mem_functor2<void, DirBrowser, Gtk::TreePath const&, Gtk::TreeViewColumn*>::operator() (this=0x5555585f68e8, _A_a1=..., _A_a2=@0x7fffffffb9c8: 0x555557ba7ca0) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:2143
No locals.
#20 0x0000555555bee659 in sigc::adaptor_functor<sigc::bound_mem_functor2<void, DirBrowser, Gtk::TreePath const&, Gtk::TreeViewColumn*> >::operator()<Gtk::TreePath const&, Gtk::TreeViewColumn* const&> (this=0x5555585f68e0, _A_arg1=..., 
    _A_arg2=@0x7fffffffb9c8: 0x555557ba7ca0) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:108
No locals.
#21 0x0000555555bedab0 in sigc::internal::slot_call2<sigc::bound_mem_functor2<void, DirBrowser, Gtk::TreePath const&, Gtk::TreeViewColumn*>, void, Gtk::TreePath const&, Gtk::TreeViewColumn*>::call_it (rep=0x5555585f68b0, a_1=..., a_2=@0x7fffffffb9c8: 0x555557ba7ca0)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:184
        typed_rep = 0x5555585f68b0
```

**Comment by Beep6581** [comment]
I double-clicked on the same folder twice:
```
Thread 1 "rawtherapee" received signal SIGABRT, Aborted.
0x00007ffff13e332b in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff13e332b in raise () from /lib64/libc.so.6
#1  0x00007ffff13e49a1 in abort () from /lib64/libc.so.6
#2  0x00007ffff14229dc in ?? () from /lib64/libc.so.6
#3  0x00007ffff14289ff in ?? () from /lib64/libc.so.6
#4  0x00007ffff142926e in ?? () from /lib64/libc.so.6
#5  0x0000555555d18e2b in IdleRegister::destroy (this=0x7fff700046e0) at /home/morgan/programs/code-rawtherapee/rtgui/guiutils.cc:92
#6  0x0000555555d18b16 in IdleRegister::~IdleRegister (this=0x7fff700046e0, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/guiutils.cc:43
#7  0x0000555555caee47 in FileBrowserEntry::~FileBrowserEntry (this=0x7fff70004520, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/filebrowserentry.cc:68
#8  0x0000555555caeeec in FileBrowserEntry::~FileBrowserEntry (this=0x7fff70004520, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtgui/filebrowserentry.cc:86
#9  0x0000555555c9363f in FileBrowser::close (this=0x55555a56d450) at /home/morgan/programs/code-rawtherapee/rtgui/filebrowser.cc:680
#10 0x0000555555cc479e in FileCatalog::closeDir (this=0x55555a56cb80) at /home/morgan/programs/code-rawtherapee/rtgui/filecatalog.cc:537
#11 0x0000555555cc4f9c in FileCatalog::dirSelected (this=0x55555a56cb80, dirname=..., openfile=...) at /home/morgan/programs/code-rawtherapee/rtgui/filecatalog.cc:601
#12 0x0000555555ce7981 in sigc::bound_mem_functor2<void, FileCatalog, Glib::ustring const&, Glib::ustring const&>::operator() (this=0x55555a6d3b48, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:2143
#13 0x0000555555ce5cd3 in sigc::adaptor_functor<sigc::bound_mem_functor2<void, FileCatalog, Glib::ustring const&, Glib::ustring const&> >::operator()<Glib::ustring const&, Glib::ustring const&> (this=0x55555a6d3b40, _A_arg1=..., _A_arg2=...)
    at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:108
#14 0x0000555555ce3dbc in sigc::internal::slot_call<sigc::bound_mem_functor2<void, FileCatalog, Glib::ustring const&, Glib::ustring const&>, void, Glib::ustring const&, Glib::ustring const&>::call_it (rep=0x55555a6d3b10, a_#0=..., a_#1=...)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:429
#15 0x0000555555bed3fd in sigc::internal::signal_emit2<void, Glib::ustring const&, Glib::ustring const&, sigc::nil>::emit (impl=0x55555a6d3af0, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/signal.h:1296
#16 0x0000555555bec329 in sigc::signal2<void, Glib::ustring const&, Glib::ustring const&, sigc::nil>::emit (this=0x555557b4cd60, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/signal.h:3104
#17 0x0000555555beaead in sigc::signal2<void, Glib::ustring const&, Glib::ustring const&, sigc::nil>::operator() (this=0x555557b4cd60, _A_a1=..., _A_a2=...) at /usr/include/sigc++-2.0/sigc++/signal.h:3120
#18 0x0000555555be5e4d in DirBrowser::row_activated (this=0x555557b4cc00, path=..., column=0x555557b4cca0) at /home/morgan/programs/code-rawtherapee/rtgui/dirbrowser.cc:390
#19 0x0000555555bef028 in sigc::bound_mem_functor2<void, DirBrowser, Gtk::TreePath const&, Gtk::TreeViewColumn*>::operator() (this=0x555558444b28, _A_a1=..., _A_a2=@0x7fffffffb9c8: 0x555557b4cca0) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:2143
#20 0x0000555555bee659 in sigc::adaptor_functor<sigc::bound_mem_functor2<void, DirBrowser, Gtk::TreePath const&, Gtk::TreeViewColumn*> >::operator()<Gtk::TreePath const&, Gtk::TreeViewColumn* const&> (this=0x555558444b20, _A_arg1=..., 
    _A_arg2=@0x7fffffffb9c8: 0x555557b4cca0) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:108
#21 0x0000555555bedab0 in sigc::internal::slot_call2<sigc::bound_mem_functor2<void, DirBrowser, Gtk::TreePath const&, Gtk::TreeViewColumn*>, void, Gtk::TreePath const&, Gtk::TreeViewColumn*>::call_it (rep=0x555558444af0, a_1=..., a_2=@0x7fffffffb9c8: 0x555557b4cca0)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:184
#22 0x00007ffff401d8b7 in ?? () from /usr/lib64/libgtkmm-3.0.so.1
#23 0x00007ffff56e5e05 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#24 0x00007ffff56f7d56 in ?? () from /usr/lib64/libgobject-2.0.so.0
#25 0x00007ffff57002b6 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#26 0x00007ffff57004e2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#27 0x00007ffff70cd6f3 in ?? () from /usr/lib64/libgtk-3.so.0
#28 0x00007fffecc1b0dc in ffi_call_unix64 () from /usr/lib64/libffi.so.6
#29 0x00007fffecc1abe5 in ffi_call () from /usr/lib64/libffi.so.6
#30 0x00007ffff56e6a1c in g_cclosure_marshal_generic_va () from /usr/lib64/libgobject-2.0.so.0
#31 0x00007ffff56e6034 in ?? () from /usr/lib64/libgobject-2.0.so.0
#32 0x00007ffff56ffbc8 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#33 0x00007ffff57004e2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#34 0x00007ffff6f541f7 in ?? () from /usr/lib64/libgtk-3.so.0
#35 0x00007ffff56e8b6e in g_cclosure_marshal_VOID__BOXEDv () from /usr/lib64/libgobject-2.0.so.0
#36 0x00007ffff56e6034 in ?? () from /usr/lib64/libgobject-2.0.so.0
#37 0x00007ffff56ffbc8 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#38 0x00007ffff57004e2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#39 0x00007ffff6f512ab in ?? () from /usr/lib64/libgtk-3.so.0
#40 0x00007ffff6f527eb in ?? () from /usr/lib64/libgtk-3.so.0
#41 0x00007ffff6f553f5 in ?? () from /usr/lib64/libgtk-3.so.0
#42 0x00007ffff6f2410b in gtk_event_controller_handle_event () from /usr/lib64/libgtk-3.so.0
#43 0x00007ffff70dd1a3 in ?? () from /usr/lib64/libgtk-3.so.0
#44 0x00007ffff6f9adca in ?? () from /usr/lib64/libgtk-3.so.0
#45 0x00007ffff56e6034 in ?? () from /usr/lib64/libgobject-2.0.so.0
#46 0x00007ffff56ff68b in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#47 0x00007ffff57004e2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#48 0x00007ffff70dea34 in ?? () from /usr/lib64/libgtk-3.so.0
#49 0x00007ffff6f97e8e in ?? () from /usr/lib64/libgtk-3.so.0
#50 0x00007ffff6f99e11 in gtk_main_do_event () from /usr/lib64/libgtk-3.so.0
#51 0x00007ffff6ac3165 in ?? () from /usr/lib64/libgdk-3.so.0
#52 0x00007ffff6af2ff2 in ?? () from /usr/lib64/libgdk-3.so.0
#53 0x00007ffff540c5dd in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#54 0x00007ffff540c888 in ?? () from /usr/lib64/libglib-2.0.so.0
```

**Comment by Beep6581** [comment]
@agriggio I could not reproduce this using 0f0f76df so the problem lies in 5d4bd4b3529b14f929eaf887b5413c95f961dba2 or d8e0207b9a2b3a38a68f6fec3633622b2b2b761d

**Comment by agriggio** [comment]
I'll take a look

**Comment by agriggio** [comment]
@Beep6581 this should do:

```diff
diff --git a/rtgui/guiutils.cc b/rtgui/guiutils.cc
--- a/rtgui/guiutils.cc
+++ b/rtgui/guiutils.cc
@@ -91,6 +91,7 @@
         DataWrapper *w = static_cast<DataWrapper *>(id.first);
         delete w;
     }
+    ids.clear();
     mutex.unlock();
 }
 
```

(I just pushed it, in fact)

**Comment by Beep6581** [comment]
Fix confirmed.

Is it just me, or does this File Browser feel faster now?
