### ISSUE TITLE
Deadlock when switching large folders

### ISSUE THREAD

**Issue by Floessie** [Beep6581/RawTherapee#4254]
Merry Christmas,

When trying to reproduce another oddity I encountered a reproducible deadlock of the main thread. Here's what I did:

1. Select a folder with many images.
2. Open one of those images, apply neutral, DCP tone curve, and Fattal (don't think that matters).
3. Switch back to file browser.
4. Select a subfolder with many images.
5. Quickly select the previous (base) folder while the images are indexed.

Now RT completely freezes.

Backtrace:
```
(gdb) thread apply all bt

Thread 196 (Thread 0x7fffbd7fa700 (LWP 4559)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff544787c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x0000555555ea2f03 in ThumbImageUpdater::removeJobs (this=0x5555568741e8 <ThumbImageUpdater::getInstance()::instance_>, listener=0x7fff580885e8) at /home/user/src/rawtherapee/rtgui/thumbimageupdater.cc:242
#3  0x0000555555c70d07 in FileBrowserEntry::~FileBrowserEntry (this=0x7fff58088400, __in_chrg=<optimized out>) at /home/user/src/rawtherapee/rtgui/filebrowserentry.cc:82
#4  0x0000555555c70dba in FileBrowserEntry::~FileBrowserEntry (this=0x7fff58088400, __in_chrg=<optimized out>) at /home/user/src/rawtherapee/rtgui/filebrowserentry.cc:88
#5  0x0000555555c87465 in FileCatalog::previewReady (this=0x555559505a00, dir_id=4, fdn=0x7fff58088400) at /home/user/src/rawtherapee/rtgui/filecatalog.cc:727
#6  0x0000555555e16606 in PreviewLoader::Impl::processNextJob (this=0x55555861fc00) at /home/user/src/rawtherapee/rtgui/previewloader.cc:134
#7  0x0000555555e17acc in sigc::bound_mem_functor0<void, PreviewLoader::Impl>::operator() (this=0x7fff580978d8) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
#8  0x0000555555e178aa in sigc::adaptor_functor<sigc::bound_mem_functor0<void, PreviewLoader::Impl> >::operator() (this=0x7fff580978d0) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#9  0x0000555555e17669 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, PreviewLoader::Impl>, void>::call_it (rep=0x7fff580978a0) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:114
#10 0x00007ffff459ceb2 in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#11 0x00007ffff542adce in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff542a3d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff1434494 in start_thread (arg=0x7fffbd7fa700) at pthread_create.c:333
#14 0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 190 (Thread 0x7fffceffd700 (LWP 4553)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff1436c06 in __GI___pthread_mutex_lock (mutex=0x5555568a1310) at ../nptl/pthread_mutex_lock.c:115
#2  0x0000555555d4abaf in (anonymous namespace)::myGdkLockEnter () at /home/user/src/rawtherapee/rtgui/main.cc:99
#3  0x0000555555b3ca37 in GThreadUnLock::~GThreadUnLock (this=0x7fffceffc80f, __in_chrg=<optimized out>) at /home/user/src/rawtherapee/rtgui/guiutils.h:112
#4  0x0000555555ea2f0f in ThumbImageUpdater::removeJobs (this=0x5555568741e8 <ThumbImageUpdater::getInstance()::instance_>, listener=0x7fffa0001c28) at /home/user/src/rawtherapee/rtgui/thumbimageupdater.cc:239
#5  0x0000555555c70d07 in FileBrowserEntry::~FileBrowserEntry (this=0x7fffa0001a40, __in_chrg=<optimized out>) at /home/user/src/rawtherapee/rtgui/filebrowserentry.cc:82
#6  0x0000555555c70dba in FileBrowserEntry::~FileBrowserEntry (this=0x7fffa0001a40, __in_chrg=<optimized out>) at /home/user/src/rawtherapee/rtgui/filebrowserentry.cc:88
#7  0x0000555555c87465 in FileCatalog::previewReady (this=0x555559505a00, dir_id=4, fdn=0x7fffa0001a40) at /home/user/src/rawtherapee/rtgui/filecatalog.cc:727
#8  0x0000555555e16606 in PreviewLoader::Impl::processNextJob (this=0x55555861fc00) at /home/user/src/rawtherapee/rtgui/previewloader.cc:134
#9  0x0000555555e17acc in sigc::bound_mem_functor0<void, PreviewLoader::Impl>::operator() (this=0x7fffa0071f88) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
#10 0x0000555555e178aa in sigc::adaptor_functor<sigc::bound_mem_functor0<void, PreviewLoader::Impl> >::operator() (this=0x7fffa0071f80) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#11 0x0000555555e17669 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, PreviewLoader::Impl>, void>::call_it (rep=0x7fffa0071f50) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:114
#12 0x00007ffff459ceb2 in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#13 0x00007ffff542adce in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff542a3d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff1434494 in start_thread (arg=0x7fffceffd700) at pthread_create.c:333
#16 0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fffe5a24700 (LWP 4367)):
#0  0x00007ffff116d6ad in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff54029f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5402d82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff59ea656 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff542a3d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff1434494 in start_thread (arg=0x7fffe5a24700) at pthread_create.c:333
#6  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fffe6225700 (LWP 4366)):
#0  0x00007ffff116d6ad in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff54029f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5402b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff5402b51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff542a3d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff1434494 in start_thread (arg=0x7fffe6225700) at pthread_create.c:333
#6  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fffe7098700 (LWP 4365)):
#0  0x00007ffff1879d1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff1877690 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff1434494 in start_thread (arg=0x7fffe7098700) at pthread_create.c:333
#3  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fffe7899700 (LWP 4364)):
#0  0x00007ffff1879d1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff1877690 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff1434494 in start_thread (arg=0x7fffe7899700) at pthread_create.c:333
#3  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fffe809a700 (LWP 4363)):
#0  0x00007ffff1879d1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff1877690 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff1434494 in start_thread (arg=0x7fffe809a700) at pthread_create.c:333
#3  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fffe889b700 (LWP 4362)):
#0  0x00007ffff1879d1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff1877690 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff1434494 in start_thread (arg=0x7fffe889b700) at pthread_create.c:333
#3  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7fffe909c700 (LWP 4361)):
#0  0x00007ffff1879d1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff1877690 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff1434494 in start_thread (arg=0x7fffe909c700) at pthread_create.c:333
#3  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7fffe989d700 (LWP 4360)):
#0  0x00007ffff1879d1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff1877690 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff1434494 in start_thread (arg=0x7fffe989d700) at pthread_create.c:333
#3  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7fffea09e700 (LWP 4359)):
#0  0x00007ffff1879d1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff1877690 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff1434494 in start_thread (arg=0x7fffea09e700) at pthread_create.c:333
#3  0x00007ffff1176aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7f25b00 (LWP 4355)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff1436c06 in __GI___pthread_mutex_lock (mutex=0x5555568a1310) at ../nptl/pthread_mutex_lock.c:115
#2  0x0000555555d4abaf in (anonymous namespace)::myGdkLockEnter () at /home/user/src/rawtherapee/rtgui/main.cc:99
#3  0x00007ffff6adcece in gdk_event_source_check (source=0x555556972190) at ././gdk/x11/gdkeventsource.c:300
#4  0x00007ffff54023f9 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff5402994 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff5402d82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff6f99d55 in gtk_main () at ././gtk/gtkmain.c:1312
#8  0x00007ffff3d1ffb1 in Gtk::Main::run_impl (this=<optimized out>) at main.cc:439
#9  Gtk::Main::run (window=...) at main.cc:398
#10 0x0000555555d4dc99 in main (argc=1, argv=0x7fffffffe238) at /home/user/src/rawtherapee/rtgui/main.cc:671
```

My libglib2.0 is 2.50.3-2 and libgtk-3 is 3.22.11-1 on Debian 9.3 (amd64).

Best,
Flössie

**Comment by Thanatomanic** [comment]
@Floessie Did this also get resolved by fixing #4576 ?

**Comment by heckflosse** [comment]
@Floessie @Thanatomanic 
In my tests this is also fixed now.

**Comment by Floessie** [comment]
@Thanatomanic Good catch. I wasn't even aware of this issue only half a year later. I guess, I'm getting old. Anyway: Same description and same backtrace as in #4576 and positive test from @heckflosse (:+1:). Closing.
