### ISSUE TITLE
Memory leak with TIF batch export

### ISSUE THREAD

**Issue by da-phil** [Beep6581/RawTherapee#4264]
I'm using the latest version on `dev` branch on Ubuntu 16.04.3LTS.
```
Version: 5.3-361-g5ecb05b
Branch: dev
Commit: 5ecb05b
Commit date: 2017-12-29
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
```

Since a while (not only this very version) I noticed that I get huge memory leaks when I batch export images as TIFs, no matter whether 8bit or 16bit images, whether I set any processing options or just convert with default options. I noticed that setting computationally expensive options like tonemapping and denoising leads to leaking even more memory.
Right now it's almost impossible to export more than 10 images as TIF files, it will cause a leak of around 28 GB RAM and eventually leads to a RT crash (I only have 32 GB, and 4 GB are usually already occupied by the rest of the system).
The leak seems to only occur with TIF batch export, JPG batch export works fine!

Can anybody else reproduce this issue? For me it's reproducible with every RAW file I've tried so far.
I also attached my RT options file in case it helps: [options.txt](https://github.com/Beep6581/RawTherapee/files/1594574/options.txt)

**Comment by heckflosse** [comment]
@da-phil I can not confirm the leak. I just tested saving 10 36MPixel files to uncompressed tif 16bit in queue using neutral profile. Tested on Windows 7 using 5.3-358

Edit: Saved 10 files tiff16 compressed, then 10 times tiff16 uncompressed using default profile + hdr tonemapping

![grafik](https://user-images.githubusercontent.com/13733487/34456034-03af9d46-ed8d-11e7-893c-8bea2ff3af21.png)

**Comment by gaaned92** [comment]
On W10, 16GB
```

Version: 5.3-361-g5ecb05ba
Branch: dev
Commit: 5ecb05ba
Commit date: 2017-12-29
Compiler: gcc 7.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON

```
processed 25 different files (one is 100MB) from different cameras with HDRtonemapping and denoising.
first time in tiff 16 uncompressed and second in tiff 16 compressed.
I cannot observe memory leak on the Windows task manager.

**Comment by Beep6581** [comment]
Saved 30 10.1MP HDR DNGs to 16-bit uncompressed TIFF using HDR Tone Mapping and Noise Reduction, haven't noticed any issues.
`5.3-362-g`d7f96c29 (branch procparams-metadata-mode, one commit behind dev)
![imgur-2017_12_30-19 45 57](https://user-images.githubusercontent.com/5844619/34456589-68ded54e-ed9a-11e7-9806-1ef6df0220ef.png)

**Comment by da-phil** [comment]
@heckflosse I also tried out D800 files, with the same result.

Hmm ok, maybe the leak is caused by my libtiff library (version 4.0.6, ubuntu16.04.3 default).
I saw that there are a couple of memory leaks reported here, but only for versions 4.0.7 and 4.0.8:
https://www.cvedetails.com/vulnerability-list/vendor_id-2224/year-2017/Libtiff.html

Which version of libtiff do you link RT to?

**Comment by Beep6581** [comment]
media-libs/tiff-4.0.8

**Comment by heckflosse** [comment]
On Windows:

```
mingw64/mingw-w64-x86_64-libtiff 4.0.9-1 [Installiert]
```

**Comment by heckflosse** [comment]
@da-phil 

> I noticed that setting computationally expensive options like tonemapping and denoising leads to leaking even more memory.

I would have guessed the leak is in libtiff, but then there is also your above statement which does not fit...

**Comment by da-phil** [comment]
@heckflosse actually I'm not so sure about it anymore, I did another test of exporting TIFF images manually, not using the batch exporter, it shows the same behavior, however it's leaking way less memory, I could export 26 images by only "losing" around 2-3 GB. When I use the batch exporter on 10 different images I lose around 16 GB! This is quite weird.

**Comment by Beep6581** [comment]
@da-phil can you try using a newer libtiff and using `./tools/build-rawtherapee` ?

**Comment by heckflosse** [comment]
@da-phil can you reproduce the leak when you add for example 30 images to the queue, then close rt, start rt and start the queue?

**Comment by Hombre57** [comment]
My 0.0002 cents : could this be related to the compiler ?

**Comment by Beep6581** [comment]
@da-phil and I seem to be using the same compiler, GCC 5.4.0.

**Comment by da-phil** [comment]
@heckflosse nope, same effect, I could not even process more than 13 images :D
![screenshot from 2018-01-02 00-47-23](https://user-images.githubusercontent.com/810285/34471980-bfc99746-ef56-11e7-8f61-420947bb8b1a.png)

@Beep6581 I don't have much time to try it out so far, but I highly suspect libtiff! I'll keep you updated once I could get a newer version of libtiff to make tests with. Seems like a lot of effort :/

**Comment by reggybe** [comment]
Just one remark: 
In the about text of da-phil is the compiler **cc** 5.4.0 and **not gcc** 5,4,0. **cc** (compiler mostly used on Solaris) is  very different from **gcc** compiler.
He should try to recompile RT with GCC 5.4.0 and do the test again.

**Comment by Beep6581** [comment]
GCC can show up as "cc".

**Comment by Floessie** [comment]
```
$ ls -la `which cc`
lrwxrwxrwx 1 root root 20 Dez 17  2014 /usr/bin/cc -> /etc/alternatives/cc
$ ls -la /etc/alternatives/cc
lrwxrwxrwx 1 root root 12 Dez 17  2014 /etc/alternatives/cc -> /usr/bin/gcc
```

Best,
Flössie
 
**Edit**: Morgan was faster. 😋

**Comment by da-phil** [comment]
@reggybe the others are right, it's just a link to the gcc compiler suite.

Guys, I have bad news, I built the latest libtiff from master branch (on top of latest release 4.0.9) of their [gitlab repo](https://gitlab.com/libtiff/libtiff), installed it locally into `/usr/local/lib` and set `LD_LIBRARY_PATH` to prefer libs from `/usr/local/lib` to make RT find my up-to-date libtiff version over the quite old ubuntu 16.04.3 shipped version 4.0.6.
I confirmed that RT uses my local libtiff version by checking with `ldd` on the RT binary and even executing RT with strace to make sure my libtiff version was loaded, and it did:
`open("/usr/local/lib/libtiff.so.5", O_RDONLY|O_CLOEXEC) = 3`

So it seems that I have the same issue with the latest libtiff version (4.0.9) :(
Or did I miss something or did something wrong? Of course I assume there is no regression between libtiff master and release 4.0.9 :P

**Comment by Beep6581** [comment]
@da-phil can you:
```bash
rm -rvf ~/.config/RawTherapee*
rm -rvf ~/.cache/RawTherapee*

cd ~
wget https://raw.githubusercontent.com/Beep6581/RawTherapee/dev/tools/build-rawtherapee
chmod +x build-rawtherapee
./build-rawtherapee

cd /tmp
wget http://rawtherapee.com/shared/test_images/amsterdam.pef
~/programs/rawtherapee/rawtherapee amsterdam.pef
```

Then add it to the queue x times and see if you can still reproduce?

**Comment by da-phil** [comment]
Now I can't even further test, because it segfaults during processing of the first file with the following output in gdb:
```
*** Error in `/home/phil/programs/rawtherapee/rawtherapee': double free or corruption (!prev): 0x00007ffdd0082510 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffff27ff7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ffff280837a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ffff280c53c]
/home/phil/programs/rawtherapee/rawtherapee[0xa838d6]
/home/phil/programs/rawtherapee/rawtherapee[0xa8c3ec]
/home/phil/programs/rawtherapee/rawtherapee(_ZN8rtengine21batchProcessingThreadEPNS_13ProcessingJobEPNS_23BatchProcessingListenerE+0x35)[0xa8e2c5]
/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1(+0x4e67d)[0x7ffff5a4867d]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x70bb5)[0x7ffff68c3bb5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7ffff2b596ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7ffff288f3dd]
======= Memory map: ========
00400000-00e2a000 r-xp 00000000 08:62 10488938                           /home/phil/programs/rawtherapee/rawtherapee
01029000-01041000 r--p 00a29000 08:62 10488938                           /home/phil/programs/rawtherapee/rawtherapee
01041000-01045000 rw-p 00a41000 08:62 10488938                           /home/phil/programs/rawtherapee/rawtherapee
01045000-0716b000 rw-p 00000000 00:00 0                                  [heap]
....
7fffd0186000-7fffd0386000 rw-s 00000000 00:05 29065252                   /SYSV00000000 (deleted)
7fffd0386000-7fffd0391000 r-xp 00000000 103:01 10747987                  /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fffd0391000-7fffd0590000 ---p 0000b000 103:01 10747987                  /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fffd0590000-7fffd0591000 r--p 0000a000 103:01 10747987                  /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fffd0591000-7fffd0592000 rw-p 0000b000 103:01 10747987                  /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fffd0592000-7fffd0598000 rw-p 00000000 00:00 0 
7fffd0598000-7fffd05a3000 r-xp 00000000 103:01 10747990                  /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7fffd05a3000-7fffd07a2000 ---p 0000b000 103:01 10747990                  /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7fffd07a2000-7fffd07a3000 r--p 0000a000 103:01 10747990                  /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7fffd07a3000-7fffd07a4000 rw-p 0000b000 103:01 10747990                  /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7fffd07a4000-7fffd07ba000 r-xp 00000000 103:01 10747909                  /lib/x86_64-linux-gnu/libnsl-2.23.so
7fffd07ba000-7fffd09b9000 ---p 00016000 103:01 10747909                  /lib/x86_64-linux-gnu/libnsl-2.23.so
7fffd09b9000-7fffd09ba000 r--p 00015000 103:01 10747909                  /lib/x86_64-linux-gnu/libnsl-2.23.so
7fffd09ba000-7fffd09bb000 rw-p 00016000 103:01 10747909                  /lib/x86_64-linux-gnu/libnsl-2.23.so
7fffd09bb000-7fffd09bd000 rw-p 00000000 00:00 0 
7fffd09bd000-7fffd09c5000 r-xp 00000000 103:01 10747996                  /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7fffd09c5000-7fffd0bc4000 ---p 00008000 103:01 10747996                  /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7fffd0bc4000-7fffd0bc5000 r--p 00007000 103:01 10747996                  /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7fffd0bc5000-7fffd0bc6000 rw-p 00008000 103:01 10747996                  /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7fffd0bc6000-7fffd0dc7000 rw-p 00000000 00:00 0 
7fffd0dc7000-7fffd0f46000 r-xp 00000000 103:01 395235                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fffd0f46000-7fffd1146000 ---p 0017f000 103:01 395235                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fffd1146000-7fffd1156000 r--p 0017f000 103:01 395235                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fffd1156000-7fffd1157000 rw-p 0018f000 103:01 395235                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fffd1157000-7fffd115b000 rw-p 00000000 00:00 0 
7fffd115b000-7fffd130c000 r-xp 00000000 103:01 398949                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fffd130c000-7fffd150b000 ---p 001b1000 103:01 398949                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fffd150b000-7fffd1513000 r--p 001b0000 103:01 398949                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fffd1513000-7fffd1515000 rw-p 001b8000 103:01 398949                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fffd1515000-7fffd1516000 rw-p 00000000 00:00 0 
7fffd1516000-7fffd154d000 r-xp 00000000 103:01 401621                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffd154d000-7fffd174d000 ---p 00037000 103:01 401621                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffd174d000-7fffd1750000 r--p 00037000 103:01 401621                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffd1750000-7fffd1751000 rw-p 0003a000 103:01 401621                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffd1751000-7fffd1786000 r-xp 00000000 103:01 402453                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7fffd1786000-7fffd1986000 ---p 00035000 103:01 402453                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7fffd1986000-7fffd1987000 r--p 00035000 103:01 402453                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7fffd1987000-7fffd1988000 rw-p 00036000 103:01 402453                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7fffd1988000-7fffd198a000 r-xp 00000000 103:01 658570                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffd198a000-7fffd1b89000 ---p 00002000 103:01 658570                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffd1b89000-7fffd1b8a000 r--p 00001000 103:01 658570                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffd1b8a000-7fffd1b8b000 rw-p 00002000 103:01 658570                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffd1f8c000-7fffd218c000 rw-s 00000000 00:05 29130832                   /SYSV00000000 (deleted)
7fffd218c000-7fffd238c000 rw-s 00000000 00:05 29098034                   /SYSV00000000 (deleted)
7fffd238c000-7fffd238d000 ---p 00000000 00:00 0 
7fffd238d000-7fffd2b8d000 rw-p 00000000 00:00 0 
7fffd2b8d000-7fffd2bf3000 r-xp 00000000 103:01 402065                    /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5.0.511
7fffd2bf3000-7fffd2df2000 ---p 00066000 103:01 402065                    /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5.0.511
7fffd2df2000-7fffd2df4000 r--p 00065000 103:01 402065                    /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5.0.511
7fffd2df4000-7fffd2df5000 rw-p 00067000 103:01 402065                    /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5.0.511
7fffd2df5000-7fffd2df6000 rw-p 00000000 00:00 0 
7fffd2df6000-7fffd2dfc000 r-xp 00000000 103:01 658864                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so
7fffd2dfc000-7fffd2ffc000 ---p 00006000 103:01 658864                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so
7fffd2ffc000-7fffd2ffd000 r--p 00006000 103:01 658864                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so
7fffd2ffd000-7fffd2ffe000 rw-p 00007000 103:01 658864                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so
7fffd2ffe000-7fffd2fff000 ---p 00000000 00:00 0 
7fffd2fff000-7fffd37ff000 rw-p 00000000 00:00 0 
7fffd37ff000-7fffd3800000 ---p 00000000 00:00 0 
7fffd3800000-7fffd4000000 rw-p 00000000 00:00 0 
7fffd4000000-7fffd406d000 rw-p 00000000 00:00 0 
7fffd406d000-7fffd8000000 ---p 00000000 00:00 0 
7fffd8052000-7fffd8153000 rw-p 00000000 00:00 0 
7fffd8153000-7fffd81d3000 rw-s 00000000 00:05 29032480                   /SYSV00000000 (deleted)
7fffd82f7000-7fffd834f000 r--p 00000000 103:01 1443904                   /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-BI.ttf
7fffd834f000-7fffd8357000 r--s 00000000 08:62 11541921                   /home/phil/.local/share/gvfs-metadata/home-331bf43d.log
7fffd8357000-7fffd8376000 r--s 00000000 08:62 11539172                   /home/phil/.local/share/gvfs-metadata/home
7fffd8376000-7fffd837d000 r--p 00000000 103:01 1835175                   /usr/share/icons/hicolor/icon-theme.cache
7fffd837d000-7fffd8386000 r--p 00000000 103:01 1835765                   /usr/share/icons/Adwaita/icon-theme.cache
7fffd8386000-7fffd83d6000 r--p 00000000 103:01 1840657                   /usr/share/icons/Humanity/icon-theme.cache
7fffd83d6000-7fffd83ef000 r-xp 00000000 103:01 656139                    /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
7fffd83ef000-7fffd85ef000 ---p 00019000 103:01 656139                    /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
7fffd85ef000-7fffd85f2000 r--p 00019000 103:01 656139                    /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
7fffd85f2000-7fffd85f3000 rw-p 0001c000 103:01 656139                    /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
7fffd85f3000-7fffd85f8000 r-xp 00000000 103:01 656293                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
Thread 169 "rawtherapee" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff797e2700 (LWP 12925)]
0x00007ffff27bd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace 
#0  0x00007ffff27bd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff27bf02a in __GI_abort () at abort.c:89
#2  0x00007ffff27ff7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff2918e98 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff280837a in malloc_printerr (ar_ptr=<optimised out>, ptr=<optimised out>, str=0x7ffff2918fc8 "double free or corruption (!prev)", 
    action=3) at malloc.c:5006
#4  _int_free (av=<optimised out>, p=<optimised out>, have_lock=0) at malloc.c:3867
#5  0x00007ffff280c53c in __GI___libc_free (mem=<optimised out>) at malloc.c:2968
#6  0x0000000000a838d6 in rtengine::(anonymous namespace)::ImageProcessor::stage_finish() [clone .constprop.141] ()
#7  0x0000000000a8c3ec in rtengine::processImage(rtengine::ProcessingJob*, int&, rtengine::ProgressListener*, bool) [clone .constprop.131] ()
#8  0x0000000000a8e2c5 in rtengine::batchProcessingThread(rtengine::ProcessingJob*, rtengine::BatchProcessingListener*) ()
#9  0x00007ffff5a4867d in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#10 0x00007ffff68c3bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff2b596ba in start_thread (arg=0x7fff797e2700) at pthread_create.c:333
#12 0x00007ffff288f3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

After another try I got those backtraces:
```
Thread 401 "rawtherapee" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc17fa700 (LWP 19877)]
0x0000000000b9f5ab in gaussianBlur(float**, float**, int, int, double, float*, eGaussType, float**) ()
(gdb) backtrace
#0  0x0000000000b9f5ab in gaussianBlur(float**, float**, int, int, double, float*, eGaussType, float**) ()
#1  0x0000000000985d07 in rtengine::ImProcFunctions::sharpening(rtengine::LabImage*, float**, rtengine::procparams::SharpeningParams&) [clone ._omp_fn.1] ()
#2  0x00007ffff2fb543e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#3  0x00007ffff2b7a6ba in start_thread (arg=0x7fffc17fa700) at pthread_create.c:333
#4  0x00007ffff28b03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

```
Thread 424 "rawtherapee" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff59ffe700 (LWP 20328)]
__GI___libc_free (mem=0x4618a545461aee59) at malloc.c:2951
2951	malloc.c: No such file or directory.
(gdb) backtrace
#0  __GI___libc_free (mem=0x4618a545461aee59) at malloc.c:2951
#1  0x00007ffff2fb691e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x0000000000984500 in rtengine::ImProcFunctions::sharpening(rtengine::LabImage*, float**, rtengine::procparams::SharpeningParams&) ()
#3  0x0000000000a838a7 in rtengine::(anonymous namespace)::ImageProcessor::stage_finish() [clone .constprop.141] ()
#4  0x0000000000a8c3ec in rtengine::processImage(rtengine::ProcessingJob*, int&, rtengine::ProgressListener*, bool) [clone .constprop.131] ()
#5  0x0000000000a8e2c5 in rtengine::batchProcessingThread(rtengine::ProcessingJob*, rtengine::BatchProcessingListener*) ()
#6  0x00007ffff5a4867d in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#7  0x00007ffff68c3bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff2b7a6ba in start_thread (arg=0x7fff59ffe700) at pthread_create.c:333
#9  0x00007ffff28b03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Weirdly enough this only happens with the `amsterdam.pef` file. With my Olympus E-M1, Olympus E-M1mk2 and Nikon D800 files I don't see those crashes.

Should I build again and add debug symbols for more details?

**Comment by Beep6581** [comment]
@da-phil yes, please provide a stack backtrace using a debug build:
```
./build-rawtherapee -d
```

**Comment by da-phil** [comment]
After tinkering around like deleting the locally installed `libtiff` library I couldn't reproduce those crashes anymore. This kind of sucks from a standpoint of reproduction :/
Maybe it had to do with two versions of libtiff being installed...

After also deleting the RT config and cache folder the memory leak phenomena was gone!
Even with the old libtiff 4.0.6 provided by the installed ubuntu 16.04.3 system.
Now I'm really not sure what caused it, because using the old config and cache folder I could even see a memory leak with the version compiled with the build flags from the `build-rawtherapee` script.
I'll keep a close eye on this issue, I'm not happy with the result yet...

P.S.:
Previously I've been building RT by a fairly simple call to `cmake`, basically only stating the build type.
Thanks to your suggestion @Beep6581 the additional CMake flag `PROC_TARGET_NUMBER=2`
turned on  `-march=native` and now everything runs at least 2 or 3 times faster :o

**Comment by da-phil** [comment]
I'm closing this issue because I could not reproduce the behavior again, after using the latest version from master branch.

**Comment by Beep6581** [comment]
I hope you tried the latest version from `dev` branch.
