### ISSUE TITLE
Segfault saving image with edited metadata

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4265]
http://rawtherapee.com/shared/test_images/amsterdam.pef
https://filebin.net/wt6a0ofo6coc35n6/amsterdam.pef.pp3
Uncheck "Preferences > Image Processing > Metadata > Copy Exif/IPTC/XMP unchanged to the output file"
Save

```text
*** Error in `/home/morgan/programs/rawtherapee_dev_debug/rawtherapee': free(): invalid next size (fast): 0x00007fff7a6f6390 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7bb17)[0x7ffff0ec9b17]
/lib64/libc.so.6(+0x83eee)[0x7ffff0ed1eee]
/lib64/libc.so.6(+0x8483e)[0x7ffff0ed283e]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN6rtexif3TagD1Ev+0x62)[0x55555649b652]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN6rtexif12TagDirectoryD1Ev+0x89)[0x555556493bdb]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN6rtexif12TagDirectoryD0Ev+0x38)[0x555556493c62]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN6rtexif3TagD1Ev+0xc4)[0x55555649b6b4]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN6rtexif12TagDirectoryD1Ev+0x89)[0x555556493bdb]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN6rtexif12TagDirectoryD0Ev+0x38)[0x555556493c62]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN6rtexif11ExifManager16createJPEGMarkerEPKNS_12TagDirectoryERKSt3mapIN4Glib7ustringES6_St4lessIS6_ESaISt4pairIKS6_S6_EEEiiPh+0x422)[0x5555564a3880]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN8rtengine7ImageIO8saveJPEGEN4Glib7ustringEii+0x425)[0x5555560e380d]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN8rtengine7Image1610saveAsJPEGEN4Glib7ustringEii+0x67)[0x55555645d56f]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZNK4sigc18bound_mem_functor3IiN8rtengine8IImage16EN4Glib7ustringEiiEclERKS4_RKiS9_+0xc5)[0x555555ca0dc9]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZNK4sigc15adaptor_functorINS_18bound_mem_functor3IiN8rtengine8IImage16EN4Glib7ustringEiiEEEclIRS5_RiSA_EENS7_18deduce_result_typeIT_T0_T1_vvvvE4typeESC_SD_SE_+0x54)[0x555555c9ed38]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN4sigc12bind_functorILin1ENS_18bound_mem_functor3IiN8rtengine8IImage16EN4Glib7ustringEiiEES5_iiNS_3nilES7_S7_S7_EclEv+0x7e)[0x555555c9bf64]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN4sigc8internal10slot_call0INS_12bind_functorILin1ENS_18bound_mem_functor3IiN8rtengine8IImage16EN4Glib7ustringEiiEES7_iiNS_3nilES9_S9_S9_EEiE7call_itEPNS0_8slot_repE+0x44)[0x555555c98f2f]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZNK4sigc5slot0IiEclEv+0x79)[0x555555ca0675]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZNK4sigc15adaptor_functorINS_5slot0IiEEEclEv+0x3c)[0x555555c9e274]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN4sigc8internal9slot_callINS_5slot0IiEEiIEE7call_itEPNS0_8slot_repE+0x44)[0x555555c9b2dd]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN4sigc8internal12signal_emit0IiNS_3nilEE4emitEPNS0_11signal_implE+0x180)[0x555555c9b6d7]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZNK4sigc7signal0IiNS_3nilEE4emitEv+0x3c)[0x555555c98786]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN17ProgressConnectorIiE13workingThreadEv+0x39)[0x555555c95907]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZNK4sigc18bound_mem_functor0Iv17ProgressConnectorIiEEclEv+0x86)[0x555555ca2636]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZNK4sigc15adaptor_functorINS_18bound_mem_functor0Iv17ProgressConnectorIiEEEEclEv+0x3c)[0x555555ca0a06]
/home/morgan/programs/rawtherapee_dev_debug/rawtherapee(_ZN4sigc8internal10slot_call0INS_18bound_mem_functor0Iv17ProgressConnectorIiEEEvE7call_itEPNS0_8slot_repE+0x44)[0x555555c9ea85]
/usr/lib64/libglibmm-2.4.so.1(+0x57b62)[0x7ffff4531b62]
/usr/lib64/libglib-2.0.so.0(+0x87718)[0x7ffff53a4718]
/lib64/libpthread.so.0(+0x7ad3)[0x7ffff1219ad3]
/lib64/libc.so.6(clone+0x3f)[0x7ffff0f4f2ff]
======= Memory map: ========
(...)
Thread 47 "rawtherapee" received signal SIGABRT, Aborted.
[Switching to LWP 23275]
0x00007ffff0e841f1 in raise () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff0e841f1 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff0e8618a in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff0ec9b1c in ?? () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff0ed1eee in ?? () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff0ed283e in ?? () from /lib64/libc.so.6
No symbol table info available.
#5  0x000055555649b652 in rtexif::Tag::~Tag (this=0x7fff7a6f63b0, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtexif/rtexif.cc:1407
No locals.
#6  0x0000555556493bdb in rtexif::TagDirectory::~TagDirectory (this=0x7fff7a6f1fd0, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtexif/rtexif.cc:106
        i = 11
#7  0x0000555556493c62 in rtexif::TagDirectory::~TagDirectory (this=0x7fff7a6f1fd0, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtexif/rtexif.cc:108
No locals.
#8  0x000055555649b6b4 in rtexif::Tag::~Tag (this=0x7fff7a6f1f40, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtexif/rtexif.cc:1415
        i = 1
#9  0x0000555556493bdb in rtexif::TagDirectory::~TagDirectory (this=0x7fff78001410, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtexif/rtexif.cc:106
        i = 15
#10 0x0000555556493c62 in rtexif::TagDirectory::~TagDirectory (this=0x7fff78001410, __in_chrg=<optimized out>) at /home/morgan/programs/code-rawtherapee/rtexif/rtexif.cc:108
No locals.
#11 0x00005555564a3880 in rtexif::ExifManager::createJPEGMarker (root=0x7fff84004080, changeList=std::map with 1 elements = {...}, W=3888, H=2608, buffer=0x7fff7a6c91b0 "Exif") at /home/morgan/programs/code-rawtherapee/rtexif/rtexif.cc:3197
        offs = 10
        order = rtexif::MOTOROLA
        cl = 0x7fff78001410
        defTags = std::vector of length 12, capacity 12 = {0x7fff7a6f64a0, 0x7fff7a6f64f0, 0x7fff7a6f6540, 0x7fff7a6f6590, 0x7fff7a6f6600, 0x7fff7a6f6670, 0x7fff7a6f66c0, 0x7fff7a6f6730, 0x7fff7a6f67a0, 0x7fff7a6f6810, 0x7fff7a6f6880, 0x7fff7a6f68f0}
        size = 1837
#12 0x00005555560e380d in rtengine::ImageIO::saveJPEG (this=0x7fff84001e58, fname=..., quality=92, subSamp=2) at /home/morgan/programs/code-rawtherapee/rtengine/imageio.cc:1230
        size = 1147716290
        file = 0x7fff78001130
        cinfo = {err = 0x7fffc10c1470, mem = 0x7fff78001360, progress = 0x0, client_data = 0x7fff00000001, is_decompressor = 0, global_state = 101, dest = 0x7fff78001540, image_width = 3888, image_height = 2608, input_components = 3, in_color_space = JCS_RGB,
          input_gamma = 1, data_precision = 8, num_components = 3, jpeg_color_space = JCS_YCbCr, comp_info = 0x7fff78001580, quant_tbl_ptrs = {0x7fff78001940, 0x7fff780019d0, 0x0, 0x0}, dc_huff_tbl_ptrs = {0x7fff78001a60, 0x7fff78001d40, 0x0, 0x0}, ac_huff_tbl_ptrs = {
            0x7fff78001bf0, 0x7fff78001e90, 0x0, 0x0}, arith_dc_L = '\000' <repeats 15 times>, arith_dc_U = '\001' <repeats 16 times>, arith_ac_K = '\005' <repeats 16 times>, num_scans = 1, scan_info = 0x0, raw_data_in = 0, arith_code = 0, optimize_coding = 1,
          CCIR601_sampling = 0, smoothing_factor = 0, dct_method = JDCT_FLOAT, restart_interval = 0, restart_in_rows = 0, write_JFIF_header = 0, JFIF_major_version = 1 '\001', JFIF_minor_version = 1 '\001', density_unit = 0 '\000', X_density = 1, Y_density = 1,
          write_Adobe_marker = 0, next_scanline = 0, progressive_mode = 0, max_h_samp_factor = 2, max_v_samp_factor = 1, total_iMCU_rows = 326, comps_in_scan = 3, cur_comp_info = {0x7fff78001580, 0x7fff780015e0, 0x7fff78001640, 0x0}, MCUs_per_row = 243,
          MCU_rows_in_scan = 326, blocks_in_MCU = 4, MCU_membership = {0, 0, 1, 2, 0, 0, 0, 0, 0, 0}, Ss = 0, Se = 63, Ah = 0, Al = 0, master = 0x7fff78002fe0, main = 0x7fff78003650, prep = 0x7fff780030b0, coef = 0x7fff780033b0, marker = 0x7fff78003780,
          cconvert = 0x7fff78003020, downsample = 0x7fff78003040, fdct = 0x7fff78003150, entropy = 0x7fff780032e0, script_space = 0x0, script_space_size = 0}
        jerr = {pub = {error_exit = 0x5555560e0ac7 <my_error_exit(jpeg_common_struct*)>, emit_message = 0x7ffff2b34ba0, output_message = 0x7ffff2b34d30, format_message = 0x7ffff2b34c10, reset_error_mgr = 0x7ffff2b34bf0, msg_code = 0, msg_parm = {i = {1132850434,
                1133655211, 1133326850, 1134904512, 1133073169, 1137116891, 1134074990, 1135473533},
              s = "\002\355\205C\253\064\222C\002\062\215C\300D\245C\021S\211C\333\006\307Cn\234\230C}\363\255C\366M\210CŒ\215C扼C\000z?\355\375,\002\263\237\343\267C\021\020\304CSw\213\362\377\177\000\000\311\"\202C\200\244SC\036\360\214", <incomplete sequence \362>}, trace_level = 0, num_warnings = 0, jpeg_message_table = 0x555556a47e80 <jpeg_std_message_table@@LIBJPEG_6.2>, last_jpeg_message = 126, addon_message_table = 0x0, first_addon_message = 0, last_addon_message = 0}, setjmp_buffer = {{__jmpbuf = {93825007998216,
                1944388998618646193, 92, 2, 140735407988064, 140736432187136, 1944388998763349681, 5741796480724731569}, __mask_was_saved = 0, __saved_mask = {__val = {18446744073709551560, 1, 140737238966760, 280, 952, 0, 18446744073709551568, 1, 0, 0, 0,
                  140737354129680, 135, 140737354125312, 140737238899410, 12898921751861230080}}}}}
        width = 3888
        height = 2608
        buffer = 0x7fff7a6c91b0 "Exif"
        size = 0
        rowlen = 1147114267
        row = 0x0
#13 0x000055555645d56f in rtengine::Image16::saveAsJPEG (this=0x7fff84001d60, fname=..., quality=92, subSamp=2) at /home/morgan/programs/code-rawtherapee/rtengine/image16.h:84
No locals.
#14 0x0000555555ca0dc9 in sigc::bound_mem_functor3<int, rtengine::IImage16, Glib::ustring, int, int>::operator() (this=0x55555a621ee0, _A_a1=..., _A_a2=@0x55555a621f18: 92, _A_a3=@0x55555a621f1c: 2) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:2222
No locals.
#15 0x0000555555c9ed38 in sigc::adaptor_functor<sigc::bound_mem_functor3<int, rtengine::IImage16, Glib::ustring, int, int> >::operator()<Glib::ustring&, int&, int&> (this=0x55555a621ed8, _A_arg1=..., _A_arg2=@0x55555a621f18: 92, _A_arg3=@0x55555a621f1c: 2)
    at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:128
No locals.
#16 0x0000555555c9bf64 in sigc::bind_functor<-1, sigc::bound_mem_functor3<int, rtengine::IImage16, Glib::ustring, int, int>, Glib::ustring, int, int, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::operator() (this=0x55555a621ed0)
    at /usr/include/sigc++-2.0/sigc++/adaptors/bind.h:1529
No locals.
#17 0x0000555555c98f2f in sigc::internal::slot_call0<sigc::bind_functor<-1, sigc::bound_mem_functor3<int, rtengine::IImage16, Glib::ustring, int, int>, Glib::ustring, int, int, sigc::nil, sigc::nil, sigc::nil, sigc::nil>, int>::call_it (rep=0x55555a621ea0)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:114
        typed_rep = 0x55555a621ea0
---Type <return> to continue, or q <return> to quit---
#18 0x0000555555ca0675 in sigc::slot0<int>::operator() (this=0x55555f113848) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:513
No locals.
#19 0x0000555555c9e274 in sigc::adaptor_functor<sigc::slot0<int> >::operator() (this=0x55555f113840) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
No locals.
#20 0x0000555555c9b2dd in sigc::internal::slot_call<sigc::slot0<int>, int>::call_it (rep=0x55555f113810) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:461
        typed_rep = 0x55555f113810
#21 0x0000555555c9b6d7 in sigc::internal::signal_emit0<int, sigc::nil>::emit (impl=0x55555a6bba50) at /usr/include/sigc++-2.0/sigc++/signal.h:705
        slots = {slots_ = @0x55555a6bba58, placeholder = {<sigc::functor_base> = {<No data fields>}, rep_ = , blocked_ = false}}
        it = {<sigc::functor_base> = {<No data fields>}, rep_ = , blocked_ = false}
        exec = {sig_ = 0x55555a6bba50}
        r_ = 0
#22 0x0000555555c98786 in sigc::signal0<int, sigc::nil>::emit (this=0x55555a6bf750) at /usr/include/sigc++-2.0/sigc++/signal.h:2800
No locals.
#23 0x0000555555c95907 in ProgressConnector<int>::workingThread (this=0x55555a6bf750) at /home/morgan/programs/code-rawtherapee/rtgui/progressconnector.h:86
No locals.
#24 0x0000555555ca2636 in sigc::bound_mem_functor0<void, ProgressConnector<int> >::operator() (this=0x55555f574448) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
No locals.
#25 0x0000555555ca0a06 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, ProgressConnector<int> > >::operator() (this=0x55555f574440) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
No locals.
#26 0x0000555555c9ea85 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, ProgressConnector<int> >, void>::call_it (rep=0x55555f574410) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:114
        typed_rep = 0x55555f574410
#27 0x00007ffff4531b62 in ?? () from /usr/lib64/libglibmm-2.4.so.1
No symbol table info available.
#28 0x00007ffff53a4718 in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#29 0x00007ffff1219ad3 in ?? () from /lib64/libpthread.so.0
No symbol table info available.
#30 0x00007ffff0f4f2ff in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by Hombre57** [comment]
@Beep6581 Here we go :

```patch
diff --git a/rtexif/rtexif.cc b/rtexif/rtexif.cc
index affd530..b6b5b55 100644
--- a/rtexif/rtexif.cc
+++ b/rtexif/rtexif.cc
@@ -1938,17 +1938,15 @@
         count = 8 + strlen (text.c_str());
         valuesize = count;
         value = new unsigned char[valuesize];
-        strcpy ((char*)value, "ASCII");
-        value[5] = value[6] = value[7] = 0;
-        strcpy ((char*)value + 8, text.c_str());
+        memcpy((char*)value, "ASCII\0\0\0", 8);
+        memcpy((char*)value + 8, text.c_str(), valuesize - 8);
     } else {
         wchar_t *commentStr = (wchar_t*)g_utf8_to_utf16 (text.c_str(), -1, NULL, NULL, NULL);
         count = 8 + wcslen(commentStr)*2;
         valuesize = count;
         value = (unsigned char*)new char[valuesize];
-        strcpy ((char*)value, "UNICODE");
-        value[7] = 0;
-        wcscpy(((wchar_t*)value) + 4, commentStr);
+        memcpy((char*)value, "UNICODE\0", 8);
+        memcpy((char*)value + 8, (char*)commentStr, valuesize - 8);
         g_free(commentStr);
     }
 }
```

**Comment by agriggio** [comment]
@Hombre57 thanks, fix confirmed

**Comment by Beep6581** [comment]
@Hombre57 fix confirmed here too.
