### ISSUE TITLE
Segfault when changing to Saturation & Value Blending curve

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4279]
https://filebin.net/rg96z56vbce69ql6/DSC06164.ARW
https://filebin.net/rg96z56vbce69ql6/DSC06164.ARW.pp3
https://filebin.net/rg96z56vbce69ql6/options

When I change Exposure Tone Curve 2 to Saturation and Value Blending, segfault (release):
```
#0  0x0000555555bdf845 in rtengine::Color::RGB2Lab(float*, float*, float*, float*, float*, float*, float const (*) [3], int) ()
#1  0x0000555555c8b62b in rtengine::ImProcFunctions::rgbProc(rtengine::Imagefloat*, rtengine::LabImage*, rtengine::PipetteBuffer*, LUT<float>&, LUT<float>&, LUT<float>&, rtengine::SHMap*, int, LUT<float>&, LUT<float>&, LUT<float>&, float, float, rtengine::ColorGradientCurve const&, rtengine::OpacityCurve const&, bool, LUT<float>&, LUT<float>&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, double&, double&, double&, float&, float&, float&, double, int, int, rtengine::DCPProfile*, rtengine::DCPProfile::ApplyState const&, LUT<unsigned int>&) [clone._omp_fn.9] ()
```
  
```text
Version: 5.3-408-g2d37fd66
Branch: dev
Commit: 2d37fd66
Commit date: 2018-01-06
Compiler: cc 5.4.0
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by heckflosse** [comment]
I cannot reproduce, but this patch could fix it:

```
diff --git a/rtengine/curves.h b/rtengine/curves.h
index f9c991e8..47ab0fc6 100644
--- a/rtengine/curves.h
+++ b/rtengine/curves.h
@@ -1122,7 +1122,7 @@ inline void SatAndValueBlendingToneCurve::Apply (float& r, float& g, float& b) c
     Color::rgb2hsvtc(r, g, b, h, s, v);

     float dV;
-    if (newLum > lum) {
+    if (newLum >= lum) {
         // Linearly targeting Value = 1 and Saturation = 0
         const float coef = (newLum - lum) / (65535.f - lum);
         dV = (1.f - v) * coef;

```
@Beep6581 please test

**Comment by Beep6581** [comment]
Before I compile, here's the debug stack backtrace:
```text
#0  0x0000555556075777 in _mm_loadu_ps (__P=0x5553574339b0) at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/xmmintrin.h:931
No locals.
#1  LUT<float>::operator[](float __vector(4)) const (this=0x555556a57ec0 <rtengine::Color::cachef>, indexv=...) at /home/morgan/programs/code-rawtherapee/rtengine/LUT.h:362
        i = 3
        clampedIndexes = {6.0781064, 100.904045, 394.820496, -nan(0x400000)}
        indexes = {429496729606, -9223372036854775414}
        indexArray = {6, 100, 394, -2147483648}
        values = {{4770966844510419250, 4771054521972820208}, {4775087599343918336, 4775175272511351997}, {4787975907143984857, 4788063584606385815}, {5152116875399790336, 5152116875399790336}}
        temp0 = {4807730342935828256, 4807742179865700645}
        temp1 = {4773027221933227673, 4773071060664421925}
        lower = {71.295166, 92.2446747, 76.747261, 47.2997742}
        upper = {71.3303604, 92.2657013, 76.777626, 47.3387108}
        diff = {0.37109375, 0.515869141, 0.421264648, 0.653823853}
#2  0x000055555604f5d8 in rtengine::Color::RGB2Lab (R=0x7fff7c07a370, G=0x7fff7c086870, B=0x7fff7c092d70, L=0x7fff755b1e20, a=0x7fff75963360, b=0x7fff75d148a0, wp=0x7fff9fffc190, width=84) at /home/morgan/programs/code-rawtherapee/rtengine/color.cc:1822
        fx = {77.3744278, 98.7489777, 83.9875107, 47.8423347}
        fy = {75.0561676, 98.0468979, 84.6091385, 47.9046326}
        fz = {71.3082275, 92.2555237, 76.7600555, 47.3252335}
        rv = {6.21162081, 104.400383, 412.054016, -nan(0x400000)}
        bv = {5.17197895, 76.4193497, 277.411774, -nan(0x400000)}
        xv = {6.0781064, 100.904045, 394.820496, -nan(0x400000)}
        zv = {5.17392302, 76.4480743, 277.516052, -nan(0x400000)}
        gv = {5.49957943, 85.9380798, 320.308044, -nan(0x400000)}
        yv = {5.70464802, 91.2551498, 346.730896, -nan(0x400000)}
        maxMask = {0, 0}
        maxvalfv = {65535, 65535, 65535, 65535}
        c116v = {116, 116, 116, 116}
        c5242d88v = {5242.87988, 5242.87988, 5242.87988, 5242.87988}
        c500v = {500, 500, 500, 500}
        c200v = {200, 200, 200, 200}
        i = 80
#3  0x000055555610cba4 in rtengine::ImProcFunctions::rgbProc () at /home/morgan/programs/code-rawtherapee/rtengine/improcfun.cc:4521
        i = 0
        ti = 0
        ii = 0
        jj = 1120
        buffer = {real = 0x7fff7c07a370, alignment = 16 '\020', allocatedSize = 605184, unitSize = 4, data = 0x7fff7c07a370, inUse = true}
        editWhateverBuffer = 0x0
        jstart = 1120
        tH = 112
        editIFloatTmpR = 0x0
        editIFloatTmpB = 0x0
        out_rgbx = {1.21387243, 1.74562407, 1.80035675, 1.86564386, 1.88448381, 1.76968062, 1.29642057, 1.52838981, 1.44713092, 1.70408106, 1.76941848, 1.79100943, 1.89855647, 1.58459496, 1.49003613, 1.4194591, 1.45791805, 1.28994882, 1.38890278, 1.63722968, 
          1.69694638, 1.58781242, 1.55459058, 1.68856764, 1.75528932, 1.6733129, 1.46677721, 1.29253268, 1.43983424, 1.6548363, 1.51035976, 1.41341352, 1.49950719, 1.57534468, 1.61438155, 1.69266331, 1.65596271, 1.47112238, 1.34683311, 1.17099714, 0.926187873, 
          1.05872703, 1.27190614, 1.10538173, 1.07608163, 1.13053656, 1.11523843, 0.549192607, 1.03854704, 1.34725356, 1.2058748, 0.860647798, 0.879586339, 0.823537171, 0.945728838, 0.95396173, 1.23947942, 1.44581962, 0.776454151, 1.26067424, 1.22289407, 1.08590269, 
          1.08904862, 0.725406826, 0.970018566, 0.781209469, 0.992660761, 0.646182001, 0.966008782, 0.782943726, 0.938047707, 1.15989447, 0.947454512, 0.823301435, 0.936885595, 0.914250672, 1.03599083, 1.08758879, 0.978153706, 0.785270452, 0.796731949, 0.964782655, 
          0.933946967, 0.858811796, 0.826187074, 0.964340031, 1.060269, 0.97948283, 0.928436518, 0.773843527, 1.11611223, 1.03586483, 0.8736974, 0.899231255, 1.04256892, 0.715745211, 0.659220278, 0.865809202, 0.87117064, 0.548441708, 0.801147938, 0.804703355, 
          1.06736422, 0.817703068, 0.537261367, 0.789197683, 0.905942619, 0.972893476, 1.09187412, 0.974889398, 1.02869129, 1.21215236, 1.04675293, 1.15497756, 1.05499768, 0.888291121, 0.808560848, 0.713739872, 0.837051988, 0.750496864, 0.659057081, 0.535303533, 
          0.813749194, 0.96583277, 0.948195696, 0.90176034, 0.74746269, 1.01984906, 1.05765033, 1.16834211, 1.02628291, 0.947076678, 0.864558995, 0.550392091, 0.676301956, 0.6833933, 0.915090799, 0.68702352, 0.592523932, 1.1566751, 1.16181338, 0.903258801, 0.949899316, 
          1.17144358, 1.46385765, 1.08539462, 0.899541199, 0.375930965, 0.721560121, 0.653492689, 0.972885728, 0.921649575, 1.22739959, 1.02669978, 1.02286851, 1.23880851, 0.878200829, 1.30415654, 1.16729069, 1.02538145, 0.912559688, 0.806526303, 0.876422405, 
          0.937796354, 1.05775905, 1.07429361, 0.980474591, 1.18279552, 1.20651543, 1.1451633, 1.13388324, 1.08995724, 0.919762731, 0.768852711, 0.576654792, 0.767126203, 0.822386742, 1.06973648, 1.07174361, 0.852899194, 0.755098701, 0.813483357, 0.97331655, 
          0.816894829, 0.804809213, 0.926582575, 0.824724972, 0.743982196, 0.6801489, 0.749460518, 0.72172749, 0.870631218, 0.9836694, 0.851161659, 0.712086976, 0.856978536, 0.65905571, 0.860630274, 0.591207564, 0.890260041...}
        editIFloatBuffer = 0x0
        rtemp = 0x7fff7c07a370
        btemp = 0x7fff7c092d70
        istart = 0
        editIFloatTmpG = 0x0
        gtemp = 0x7fff7c086870
        editWhateverTmp = 0x0
        perChannelSizeBytes = 50432
        tW = 1204
        histToneCurveThr = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        working = 0x7fff752fd060
        lab = 0x7fff752f7b10
---Type <return> to continue, or q <return> to quit---
        hltonecurve = @0x55555d9f7580: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, maxIndexFloat = 65535, data = 0x55555dc22000, clip = 1, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 
            65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        shtonecurve = @0x55555d9f75f0: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, maxIndexFloat = 65535, data = 0x55555dc62020, clip = 2, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 
            65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        tonecurve = @0x55555d9f7660: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, maxIndexFloat = 65535, data = 0x55555dca2040, clip = 0, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 
            65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        shmap = 0x0
        sat = 0
        rCurve = @0x55555d9f8810: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        gCurve = @0x55555d9f8880: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        bCurve = @0x55555d9f88f0: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        satLimit = 0.300000012
        satLimitOpacity = 1
        ctColorCurve = @0x55555d9f8a60: {_vptr.ColorGradientCurve = 0x555556982408 <vtable for rtengine::ColorGradientCurve+16>, lut1 = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, 
            upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}, lut2 = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, 
            upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}, lut3 = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, 
            upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}, low = 0, high = 0}
        ctOpacityCurve = @0x55555d9f8bd0: {_vptr.OpacityCurve = 0x555556982428 <vtable for rtengine::OpacityCurve+16>, lutOpacityCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, 
            upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        opautili = false
        clToningcurve = @0x55555d9f7a80: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, maxIndexFloat = 65535, data = 0x55555de82140, clip = 0, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {
            65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        cl2Toningcurve = @0x55555d9f7af0: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, maxIndexFloat = 65535, data = 0x55555dec2160, clip = 0, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {
            65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        customToneCurve1 = @0x55555d9f8960: {_vptr.ToneCurve = 0x555556980748 <vtable for rtengine::ToneCurve+16>, lutToneCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, maxIndexFloat = 65535, data = 0x7fffac0986a0, clip = 268435455, 
            size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}}
        customToneCurve2 = @0x55555d9f89e0: {_vptr.ToneCurve = 0x555556980748 <vtable for rtengine::ToneCurve+16>, lutToneCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, maxIndexFloat = 65535, data = 0x7fffac058680, clip = 268435455, 
            size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}}
        customToneCurvebw1 = @0x55555d9f9280: {_vptr.ToneCurve = 0x555556980748 <vtable for rtengine::ToneCurve+16>, lutToneCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, 
            upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        dcpProf = 0x7fffc80db9d0
        asIn = @0x7fff9fffd300: {data = std::unique_ptr<rtengine::DCPProfile::ApplyState::Data> containing 0x7fffac0158a0}
        histToneCurve = @0x7fff9fffd520: {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, maxIndexFloat = -9.99999975e-06, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, 
          dirty = true}
        this = 0x55555d9f7388
        tmpImage = 0x0
        editImgFloat = 0x0
        editWhatever = 0x0
        editID = EUID_None
        h_th = 0
        s_th = 0
        processSH = false
        wprof = 0x55555659e200 <_ZL12xyz_prophoto>
        wiprof = 0x55555659e260 <_ZL12prophoto_xyz>
        toxyz = {{0.827291906, 0.140211254, 0.0325175263}, {0.288040191, 0.711874127, 8.56999977e-05}, {0, 0, 1.00037587}}
        equalR = 2.47144032
        equalG = 1
        equalB = 8306.58301
        wip = {{1.3459433000000001, -0.25560749999999999, -0.051111799999999999}, {-0.5445989, 1.5081673, 0.020535100000000001}, {0, 0, 1.2118127999999999}}
        wp = {{0.79767489999999996, 0.1351917, 0.031353399999999997}, {0.28804020000000002, 0.71187409999999995, 8.5699999999999996e-05}, {0, 0, 0.82521}}
        mixchannels = false
        hCurve = 0x0
        sCurve = 0x0
        vCurve = 0x0
        bwlCurve = 0x0
        hCurveEnabled = false
        sCurveEnabled = false
        vCurveEnabled = false
        bwlCurveEnabled = false
        hald_clut = std::shared_ptr (empty) 0x0
        clutAndWorkingProfilesAreSame = false
        xyz2clut = 0x0
        clut2xyz = 0x0
---Type <return> to continue, or q <return> to quit---
        v_work2xyz = {{{-1.08352699e-19, 4.59163468e-41, -1.82005799e-12, 4.59163468e-41}, {0, 0, 8.43581676e-43, 0}, {5.63321983e-43, 0, 4.33847146e+13, 3.0611365e-41}}, {{-1337.78149, 347.706543, 295.778809, 166.30957}, {67.5004883, -77.0361328, 111.199707, 
              261.414551}, {252.910645, 53.8554688, -18.7641602, -33.4858398}}, {{-1.81901369e-12, 4.59163468e-41, -109.645508, 30.3671875}, {206.561768, 183.282227, 3.79105678e+25, 1.71157702e+27}, {-1.81901369e-12, 4.59163468e-41, -1.81899634e-12, 4.59163468e-41}}}
        v_xyz2clut = {{{2.24207754e-44, 0, 3.79105678e+25, 1.71157702e+27}, {1.4573504e-42, 0, -1.81899634e-12, 4.59163468e-41}, {2.24207754e-44, 0, 8.43021156e-42, 0}}, {{1.4573504e-42, 0, -1.08321576e-19, 4.59163468e-41}, {0, 0, 3.79105678e+25, 1.71157702e+27}, {
              -1.08321162e-19, 4.59163468e-41, 4.30543544e+13, 3.0611365e-41}}, {{-1.08321576e-19, 4.59163468e-41, -1.08321679e-19, 4.59163468e-41}, {8.96831017e-44, 0, 3.79105678e+25, 1.71157702e+27}, {-1.08321473e-19, 4.59163468e-41, -2.01165126e-12, 4.59163468e-41}}}
        v_clut2xyz = {{{-1.08321473e-19, 4.59163468e-41, 4.3052706e+13, 3.0611365e-41}, {-1.08321576e-19, 4.59163468e-41, -1.08321679e-19, 4.59163468e-41}, {-2.01254638e-12, 4.59163468e-41, 3.79105678e+25, 1.71157702e+27}}, {{-1.0832199e-19, 4.59163468e-41,
              4.30486753e+13, 3.0611365e-41}, {-2.01165473e-12, 4.59163468e-41, 1.40129846e-45, 4.59163468e-41}, {-2.01165473e-12, 4.59163468e-41, 3.79105678e+25, 1.71157702e+27}}, {{-2.01388559e-12, 4.59163468e-41, -1.08326849e-19, 4.59163468e-41}, {-1.08322507e-19,
              4.59163468e-41, 8.43021156e-42, 0}, {5.62761463e-42, 0, 2.6604031e+36, 4.59163468e-41}}}
        v_xyz2work = {{{0, 0, -1.08323127e-19, 4.59163468e-41}, {-2.01121064e-12, 4.59163468e-41, 3.79105678e+25, 1.71157702e+27}, {-1.08322713e-19, 4.59163468e-41, 4.30543544e+13, 3.0611365e-41}}, {{-1.08323127e-19, 4.59163468e-41, -1.0832323e-19, 4.59163468e-41}, {
              1.84971397e-43, 0, 3.79105678e+25, 1.71157702e+27}, {-1.08323024e-19, 4.59163468e-41, -2.01524908e-12, 4.59163468e-41}}, {{-1.08323024e-19, 4.59163468e-41, 4.3052706e+13, 3.0611365e-41}, {-1.08323127e-19, 4.59163468e-41, -1.0832323e-19, 4.59163468e-41}, {
              -2.01662298e-12, 4.59163468e-41, 3.79105678e+25, 1.71157702e+27}}}
        film_simulation_strength = 1
        exp_scale = 0.25
        comp = 0.100000001
        hlrange = 62259.1016
        isProPhoto = true
        curveMode = rtengine::procparams::ToneCurveParams::TcMode::PERCEPTUAL
        curveMode2 = rtengine::procparams::ToneCurveParams::TcMode::SATANDVALBLENDING
        highlight = true
        hasToneCurve1 = true
        hasToneCurve2 = true
        beforeCurveMode = rtengine::procparams::BlackWhiteParams::TcMode::STD_BW
        hasToneCurvebw1 = false
        ptc1ApplyState = {Working2Prophoto = {{5.63321983e-43, 0, 1.83670992e-40}, {0, 5.73971851e-42, 0}, {1.40129846e-45, 1.71157702e+27, -148.790039}}, Prophoto2Working = {{-206.846191, 3.79105678e+25, 1.71157702e+27}, {-1.08348976e-19, 4.59163468e-41,
              -1.8593807e-12}, {4.59163468e-41, -nan(0x7fff68), -nan(0x7fffff)}}, cmul_contrast = 1.00007641, isProphoto = true}
        ptc2ApplyState = {Working2Prophoto = {{-1.85940846e-12, 4.59163468e-41, 8.43581676e-43}, {0, 5.63321983e-43, 0}, {-1.13782323e+30, 4.59163468e-41, 8.43581676e-43}}, Prophoto2Working = {{0, 5.63321983e-43, 0}, {-1.08348976e-19, 4.59163468e-41, 3.79105678e+25}, {
              1.71157702e+27, 156.037109, 269.30957}}, cmul_contrast = -1.08345874e-19, isProphoto = 255}
        hasColorToning = false
        strProtect = 0.5
        RedLow = 1
        GreenLow = 1
        BlueLow = 1
        RedMed = 1
        GreenMed = 1
        BlueMed = 1
        RedHigh = 1
        GreenHigh = 1
        BlueHigh = 1
        SatLow = 0.800000012
        SatHigh = 0.600000024
        Balan = 0
        chMixRR = 100
        chMixRG = 0
        chMixRB = 0
        chMixGR = 0
        chMixGG = 100
        chMixGB = 0
        chMixBR = 0
        chMixBG = 0
        chMixBB = 100
        shHighlights = 0
        shShadows = 0
        blackwhite = false
        algm = 0
        gammabwr = 1
        gammabwg = 1
        gammabwb = 1
        hasgammabw = false
        toneCurveHistSize = 0
        histToneCurveCompression = 0
        lumimulf = {0.288040191, 0.711874127, 8.56999977e-05}
#4  0x00007ffff165b18e in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgomp.so.1
No symbol table info available.
#5  0x00007ffff1219ad3 in ?? () from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#6  0x00007ffff0f4f2ff in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by heckflosse** [comment]
This one should be better:

```
diff --git a/rtengine/curves.h b/rtengine/curves.h
index f9c991e8..48cc800e 100644
--- a/rtengine/curves.h
+++ b/rtengine/curves.h
@@ -1115,9 +1115,14 @@ inline void SatAndValueBlendingToneCurve::Apply (float& r, float& g, float& b) c
     g = CLIP(g);
     b = CLIP(b);

+
     const float lum = (r + g + b) / 3.f;
     const float newLum = lutToneCurve[lum];

+    if (newLum == lum) {
+        return;
+    }
+
     float h, s, v;
     Color::rgb2hsvtc(r, g, b, h, s, v);

```

**Comment by Beep6581** [comment]
That fixes it.
