### ISSUE TITLE
Segfault on my new W64 builds.

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#4342]
Since yesterday 01/29 my new W64 builds crash on start. The build chain was not modified and I think no MSYS2 updating was made. 

```

Reading symbols from rawtherapee-debug...done.
(gdb) run
Starting program: Y:\5.3-544-g4ce9b0f01\rawtherapee-debug.exe
[New Thread 94780.0x16ddc]
[New Thread 94780.0x17380]
[New Thread 94780.0x16d34]
[New Thread 94780.0x16d58]
[New Thread 94780.0x16eec]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006fce275d in ?? () from Y:\5.3-544-g4ce9b0f01\libstdc++-6.dll
(gdb) bt full
#0  0x000000006fce275d in ?? () from Y:\5.3-544-g4ce9b0f01\libstdc++-6.dll
No symbol table info available.
#1  0x00000000664dd72a in ?? () from Y:\5.3-544-g4ce9b0f01\libglibmm-2.4-1.dll
No symbol table info available.
#2  0x00000000005a40bf in main (argc=<optimized out>, argv=<optimized out>)
    at D:/RAWTHERAPEE/RTSOURCE/rawtherapee/rtgui/main.cc:485
        exname = "\000\000\000\000\000\000\000\000ؚ▒\000\000\000\000\000\000\000@\000\000\000\000\000\000▒$\b\000\000\000\000\000\000\000\001\000\000\000\000▒\000▒\000\000\000\000\000\070▒▒\b\000\000\000\000\\\000D\000e\000v\000i\000c\000e\000\\\000H\000a\000r\000d\000d\000i\000s\000k\000V\000o\000l\000u\000m\000e\000\061\000\060\000\\\000R\000A\000W\000T\000H\000E\000R\000A\000P\000E\000E\000\\\000\065\000.\000\063\000-\000\065\000\064\000\064\000-\000g\000\064\000c\000e\000\071\000b\000\060\000f\000\060\000\061\000\\\000r\000a\000w\000t\000\000▒▒▒▒▒▒▒▒\023▒\v\000\000\000\000\000\001\000\000\000\000\000\000"...
        exePath = {static npos = 18446744073709551615, string_ = {
            static npos = 18446744073709551615,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
              _M_p = 0x4a1152d600000 <error: Cannot access memory at address 0x4a1152d600000>}, _M_string_length = 140712091872186, {
              _M_local_buf = "\000\000\000\000\000\000\000\000k▒\b%\000\000\000", _M_allocated_capacity = 0}}}
        exnameU = L"\000\000\000\000$\x2004\000\000\000\000\000\000\000\020\000\000\v\000\000\000\004\005\000\000\000\275\376\xffff\004\000`\054\100\273\376\xffff\160\004\000\000\000\x30c\212\013\000\000\120\001\212\013\000\000\177\000\000\000\000\235\024\000\000\160\024\000\000\000\160\004\000\000\000\000\000\000\000\x1bb0\xcef\000\000\177\000\000\000\000\000\000\000`\054\100\000\000b\054\100\000\000H\000\000\000\200\004\000\000\000`\000\000\000\x1b40\xcef\000\000\x1b80\xcef\000\000\x738\212\013\000\000\004\000\000\000\111\001\004\114\000\000\111\001\004\114\000\000\000\x307\000\000\002\x604", '\000' <repeats 14 times>, "\111\001\004\114\000\000\x1ac0\xcef\000\000\000\000\000\000c\000\120\000\000\220\141\160\027\372\177\000\x1ab0\xcef\000\000\231\152\112\031\372\177\000\000\212\013\000\000\000\212\013\000\000\000\000\000\000\372\117\130\031\372\177\000\000\212\013\000\000c\000\120\000\000\000\000\000\000h\000\100\000\000"...
        consoleOpened = <optimized out>
        ret = <optimized out>
(gdb)
```

Installer   `RawTherapee_buggy_5.3-544-g4ce9b0f01_WinVista_64.zip` 
available at 
https://keybase.pub/gaaned92/RTW64NightlyBuilds/

**Comment by gaaned92** [comment]
Correction: following packages were updated on 01/29 morning
```
ncurses
headers-git
binutils
```
I am going to roll back those packages.

**Comment by Beep6581** [comment]
Probably this:
https://github.com/Alexpux/MINGW-packages/issues/3330

**Comment by gaaned92** [comment]
@Beep6581  that's it
Runs ok with previous binutils version
I let it open for other Windows builders until it is corrected.

**Comment by gaaned92** [comment]
MSYS2/binutils downgraded now.

**Comment by gaaned92** [comment]
Issue closed
