### ISSUE TITLE
Freeze or crash using the AWB temperature bias adjuster

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4545]
To reproduce:
1) open amsterdam.pef
2) apply neutral profile
3) set white balance to automatic
4) move the AWB temperature bias adjuster like a maniac

=> 

either a freeze without console output
or a freeze with this console output
```
(rawtherapee.exe:6760): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:6760): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:6760): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:6760): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:6760): GLib-WARNING **: corrupted double-linked list detected
```
or a segfault with this console output
```
(rawtherapee.exe:7964): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:7964): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:7964): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:7964): GLib-WARNING **: corrupted double-linked list detected

(rawtherapee.exe:7964): GLib-WARNING **: corrupted double-linked list detected

(Segmentation fault

```

Version information:
```
Version: 5.4-274-gdfdf4bf39
Branch: dev
Commit: dfdf4bf39
Commit date: 2018-05-09
Compiler: gcc 7.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by heckflosse** [comment]
Maybe related: When moving the adjuster around zero I sometimes get this
![grafik](https://user-images.githubusercontent.com/13733487/39872167-72760ff8-5467-11e8-98c6-45efc0a3f64f.png)

**Comment by Floessie** [comment]
The relevant threads (non-debug build):

```
(gdb) thread apply all bt

Thread 262 (Thread 0x7fff58ea5700 (LWP 3530)):
#0  0x00007fffed90ea4b in ?? () from /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#1  0x00007fffed90ff62 in pixman_region32_union () from /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#2  0x00007ffff5f3c4f7 in cairo_region_union () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#3  0x00007ffff6ac49dc in impl_window_add_update_area (region=0x7fff78004040, impl_window=0x5555563f44b0) at ././gdk/gdkwindow.c:4330
#4  gdk_window_invalidate_maybe_recurse_full (window=0x5555563f44b0, region=0x7fff78003f40, child_func=<optimized out>, user_data=0x0) at ././gdk/gdkwindow.c:4464
#5  0x00007ffff70e9222 in gtk_widget_queue_draw_area (widget=widget@entry=0x55555a3f52d0, x=249, y=56, width=<optimized out>, height=18) at ././gtk/gtkwidget.c:5622
#6  0x00007ffff70f073f in gtk_widget_queue_draw (widget=widget@entry=0x55555a3f52d0) at ././gtk/gtkwidget.c:5643
#7  0x00007ffff6f13ca1 in gtk_entry_recompute (entry=entry@entry=0x55555a3f52d0) at ././gtk/gtkentry.c:6204
#8  0x00007ffff6f14358 in buffer_inserted_text (buffer=<optimized out>, position=0, chars=<optimized out>, n_chars=4, entry=0x55555a3f52d0) at ././gtk/gtkentry.c:5358
#9  0x00007ffff56dbf75 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff56edf82 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff56f6bdc in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff56f6fbf in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6f1c5a1 in gtk_entry_buffer_normal_insert_text (buffer=0x55555a4839a0, position=0, chars=0x7fff780042e0 "5828", n_chars=4) at ././gtk/gtkentrybuffer.c:180
#14 0x00007ffff6f11b2a in gtk_entry_real_insert_text (editable=0x55555a3f52d0, new_text=0x7fff780042e0 "5828", new_text_length=<optimized out>, position=0x7fff58ea3934) at ././gtk/gtkentry.c:5307
#15 0x00007ffff56dbf75 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff56ee37d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff56f6bdc in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff56f746b in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6f0c9d5 in gtk_entry_insert_text (editable=0x55555a3f52d0, new_text=0x7fff780019c0 "5828", new_text_length=4, position=0x7fff58ea3934) at ././gtk/gtkentry.c:5083
#20 0x00007ffff6f19c3f in gtk_entry_set_text (entry=entry@entry=0x55555a3f52d0, text=text@entry=0x7fff780019c0 "5828") at ././gtk/gtkentry.c:7638
#21 0x00007ffff703faa2 in gtk_spin_button_default_output (spin_button=0x55555a3f52d0) at ././gtk/gtkspinbutton.c:1899
#22 0x00007ffff70400b8 in gtk_spin_button_value_changed (adjustment=0x55555a3bb5a0, spin_button=0x55555a3f52d0) at ././gtk/gtkspinbutton.c:1563
#23 0x00007ffff56dbf75 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff56edf82 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff56f6bdc in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff56f6fbf in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff6e733f7 in emit_value_changed (adjustment=0x55555a3bb5a0) at ././gtk/gtkadjustment.c:349
#28 adjustment_set_value (value=5828, adjustment=0x55555a3bb5a0) at ././gtk/gtkadjustment.c:450
#29 gtk_adjustment_set_value_internal (adjustment=0x55555a3bb5a0, value=5828, animate=<optimized out>) at ././gtk/gtkadjustment.c:545
#30 0x00007ffff70410af in gtk_spin_button_set_value (spin_button=0x55555a3f52d0, value=5828) at ././gtk/gtkspinbutton.c:2311
#31 0x000055555583470f in Adjuster::setValue(double) ()
#32 0x0000555555b82c6a in WhiteBalance::WBChanged(double, double) ()
#33 0x0000555555c2e832 in rtengine::ImProcCoordinator::updatePreviewImage(int, rtengine::Crop*) ()
#34 0x0000555555c30e8c in rtengine::ImProcCoordinator::process() ()
#35 0x00007ffff458cdfd in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#36 0x00007ffff542a3d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff1434494 in start_thread (arg=0x7fff58ea5700) at pthread_create.c:333
#38 0x00007ffff1176acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7f25b00 (LWP 3263)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff1436c06 in __GI___pthread_mutex_lock (mutex=0x55555635e310) at ../nptl/pthread_mutex_lock.c:115
#2  0x00007ffff6adcf52 in gdk_event_source_prepare (source=<optimized out>, timeout=0x7fffffffd7d4) at ././gdk/x11/gdkeventsource.c:279
#3  0x00007ffff5401edd in g_main_context_prepare () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff540291b in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff5402d82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff6f99d55 in gtk_main () at ././gtk/gtkmain.c:1312
#7  0x00007ffff3d1ffb1 in Gtk::Main::run_impl (this=<optimized out>) at main.cc:439
#8  Gtk::Main::run (window=warning: RTTI symbol not found for class 'RTWindow'
...) at main.cc:398
#9  0x000055555581e0b2 in main ()
(gdb) 
```

HTH,
Flössie

**Comment by Floessie** [comment]
@heckflosse Ingo, this fixes it for me:

```patch
diff --git a/rtgui/whitebalance.cc b/rtgui/whitebalance.cc
index 57d73b15f..1f2863635 100644
--- a/rtgui/whitebalance.cc
+++ b/rtgui/whitebalance.cc
@@ -349,6 +349,10 @@ WhiteBalance::WhiteBalance () : FoldableToolPanel(this, "whitebalance", M("TP_WB
     spotsize->signal_changed().connect( sigc::mem_fun(*this, &WhiteBalance::spotSizeChanged) );
 }
 
+WhiteBalance::~WhiteBalance()
+{
+    idle_register.destroy();
+}
 
 void WhiteBalance::enabledChanged()
 {
@@ -395,7 +399,7 @@ void WhiteBalance::adjusterChanged (Adjuster* a, double newval)
         methconn.block(true);
         opt = setActiveMethod(wbCustom.second.GUILabel);
         tempBias->set_sensitive(false);
-        
+
         cache_customWB (tVal, gVal);
         if (a != equal) {
             cache_customEqual(eVal);
@@ -632,7 +636,7 @@ void WhiteBalance::read (const ProcParams* pp, const ParamsEdited* pedited)
             // the equalizer's value is restored for the AutoWB
             equal->setValue (equal->getAddMode() ? 0.0 : pp->wb.equal);
             tempBias->setValue (tempBias->getAddMode() ? 0.0 : pp->wb.tempBias);
-            
+
             // set default values first if in ADD mode, otherwise keep the current ones
             if (temp->getAddMode() ) {
                 temp->setValue (0.0);
@@ -718,7 +722,7 @@ void WhiteBalance::write (ProcParams* pp, ParamsEdited* pedited)
 
 void WhiteBalance::setDefaults (const ProcParams* defParams, const ParamsEdited* pedited)
 {
-    
+
     equal->setDefault (defParams->wb.equal);
     tempBias->setDefault (defParams->wb.tempBias);
 
@@ -895,12 +899,28 @@ inline Gtk::TreeRow WhiteBalance::getActiveMethod ()
 
 void WhiteBalance::WBChanged(double temperature, double greenVal)
 {
-    GThreadLock lock;
-    disableListener();
-    setEnabled(true);
-    temp->setValue(temperature);
-    green->setValue(greenVal);
-    temp->setDefault(temperature);
-    green->setDefault(greenVal);
-    enableListener();
+    struct Data {
+        WhiteBalance* self;
+        double temperature;
+        double green_val;
+    };
+
+    const auto func = [](gpointer data) -> gboolean {
+        WhiteBalance* const self = static_cast<WhiteBalance*>(static_cast<Data*>(data)->self);
+        const double temperature = static_cast<Data*>(data)->temperature;
+        const double green_val = static_cast<Data*>(data)->green_val;
+        delete static_cast<Data*>(data);
+
+        self->disableListener();
+        self->setEnabled(true);
+        self->temp->setValue(temperature);
+        self->green->setValue(green_val);
+        self->temp->setDefault(temperature);
+        self->green->setDefault(green_val);
+        self->enableListener();
+
+        return FALSE;
+    };
+
+    idle_register.add(func, new Data{this, temperature, greenVal});
 }
diff --git a/rtgui/whitebalance.h b/rtgui/whitebalance.h
index ecf65f476..8603d1c59 100644
--- a/rtgui/whitebalance.h
+++ b/rtgui/whitebalance.h
@@ -77,6 +77,9 @@ protected:
     int custom_temp;
     double custom_green;
     double custom_equal;
+
+    IdleRegister idle_register;
+
     void cache_customWB    (int temp, double green); //cache custom WB setting to allow its recall
     void cache_customTemp  (int temp);               //cache Temperature only to allow its recall
     void cache_customGreen (double green);           //cache Green only to allow its recall
@@ -92,7 +95,7 @@ protected:
 public:
 
     WhiteBalance ();
-    ~WhiteBalance () {};
+    ~WhiteBalance ();
 
     static void init    ();
     static void cleanup ();
```

Best,
Flössie

**Comment by heckflosse** [comment]
@Floessie Fix confirmed. :+1: for commit. Thank you!

**Comment by Floessie** [comment]
Okay, I'll push...
