### ISSUE TITLE
Segfault when new file is created in active folder from external program

### ISSUE THREAD

**Issue by FM33** [Beep6581/RawTherapee#4686]
```
Version: 5.4-772-ge65c6786f
Branch: newlocallab
Commit: e65c6786f
Commit date: 2018-07-07
Compiler: cc 7.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: debug
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

Steps to reproduce : 
* Open RT file browser and select a folder.
* Save a new DNG file in that same folder using an external program (here hdrmerge).

Then : 
```
`Thread 28 "pool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdd2fe700 (LWP 4674)]
0x0000555556007096 in LUT<float>::operator[]<float, float, void> (
    this=0x555556a386e0 <rtengine::Color::gamma2curve>, index=-nan(0x400000))
    at /home/fabien/Programmes/rawtherapee-git/rtengine/LUT.h:454
454	        T p1 = data[idx];
(gdb) bt full
#0  0x0000555556007096 in LUT<float>::operator[]<float, float, void>(float) const (this=0x555556a386e0 <rtengine::Color::gamma2curve>, index=-nan(0x400000))
    at /home/fabien/Programmes/rawtherapee-git/rtengine/LUT.h:454
        idx = -2147483648
        diff = -nan(0x400000)
        p1 = -nan(0x400000)
        p2 = -nan(0x400000)
#1  0x00005555560a0517 in rtengine::(anonymous namespace)::copyAndClamp(rtengine::LabImage const*, unsigned char*, double const (*) [3], bool) [clone ._omp_fn.1] (src=0x555556562560 <_ZL8sRGB_xyz>, dst=0x10 <error: Cannot access memory at address 0x10>, rgb_xyz=0x0, multiThread=247) at /home/fabien/Programmes/rawtherapee-git/rtengine/iplab2rgb.cc:81
        j = 0
        z_ = -nan(0x400000)
        ra = 0x7fffcc4f8b30
        R = -nan(0x400000)
        G = -nan(0x400000)
        B = -nan(0x400000)
        x_ = -nan(0x400000)
        rL = 0x7fffcc4d1240
        rb = 0x7fffcc520420
        ix = 0
        y_ = -nan(0x400000)
        i = 0
        W = -872386992
        H = 32767
#2  0x00007ffff2eaa0e3 in GOMP_parallel () at /usr/lib/x86_64-linux-gnu/libgomp.so.1
#3  0x000055555609f5d2 in rtengine::(anonymous namespace)::copyAndClamp(rtengine::LabImage const*, unsigned char*, double const (*) [3], bool) (src=0x7fffcc006e50, dst=0x7fffcc451200 "P\b", rgb_xyz=0x555556562560 <_ZL8sRGB_xyz>, multiThread=false) at /home/fabien/Programmes/rawtherapee-git/rtengine/iplab2rgb.cc:62
        W = 247
        H = 164
#4  0x000055555609f6ac in rtengine::ImProcFunctions::lab2monitorRgb(rtengine::LabImage*, rtengine::Image8*) (this=0x7fffdd2fd6b0, lab=0x7fffcc006e50, image=0x7fffcc3abc90)
    at /home/fabien/Programmes/rawtherapee-git/rtengine/iplab2rgb.cc:150
#5  0x00005555562882ad in rtengine::Thumbnail::processImage(rtengine::procparams::ProcParams const&, rtengine::SensorType, int, rtengine::TypeInterpolation, rtengine::FramesMetaData const*, double&, bool, bool) (this=0x7fffcc004220, params=..., sensorType=rtengine::ST_BAYER, rheight=164, interp=rtengine::TI_Bilinear, metadata=0x7fffc00024b8, myscale=@0x7fffdd2fd958: 1, forMonitor=true, forHistogramMatching=false) at /home/fabien/Programmes/rawtherapee-git/rtengine/rtthumbnail.cc:1396
        imgNum = 0
        camName = "PENTAX K-5 II"
        shutter = 0.00800000038
        fnumber = 8
        iso = 100
        fcomp = 0
        currWB = 
          {temp = 5802.9670715332031, green = 0.97618109184425272, equal = 1, method = "Custom", static spectMap = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double const*> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double const*> > >> = {<No data fields>}, <No data fields>}, <std::_Rb_tree_key_compare<std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {_M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}}, <std::_Rb_tree_header> = {_M_header = {_M_color = std::_S_red, _M_parent = 0x555556a6bce0, _M_left = 0x555556a4d560, _M_right = 0x555556a4a8f0}, _M_node_count = 28}, <No data fields>}}}, static Cloudy6200_spect = {39.5, 40.57, 41.630000000000003, 43.850000000000001, 46.079999999999998, 45.380000000000003, 44.689999999999998, 47.200000000000003, 49.710000000000001, 63.060000000000002, 76.409999999999997, 80.590000000000003, 84.769999999999996, 85.909999999999997, 87.049999999999997, 84.140000000000001, 81.230000000000004, 90.290000000000006, 99.349999999999994, 105.47, 111.58, 112.23, 112.87, 111.73999999999999, 110.62, 111.41, 112.2, 108.98, 105.76000000000001, 106.31999999999999, 106.89, 106.34, 105.79000000000001, 104.62, 103.45, 105.09, 106.72, 105.23999999999999, 103.76000000000001, 103.75, 103.75, 101.87, 100, 98.290000000000006, 96.579999999999998, 96.459999999999994, 96.340000000000003, 92.849999999999994, 89.370000000000005, 90.25, 91.120000000000005, 91.060000000000002, 90.989999999999995, 90.170000000000002, 89.349999999999994, 87.219999999999999, 85.099999999999994, 85.480000000000004, 85.849999999999994, 84.030000000000001, 82.200000000000003, 82.450000000000003, 82.689999999999998, 83.920000000000002, 85.150000000000006, 83.140000000000001, 81.129999999999995, 76.650000000000006, 72.170000000000002, 73.269999999999996, 74.359999999999999, 75.650000000000006, 76.950000000000003, 70.340000000000003, 63.740000000000002, 67.9---Type <return> to continue, or q <return> to quit---
80000000000004, 72.219999999999999, 74.879999999999995, 77.540000000000006, 71.590000000000003, 65.650000000000006, 56.82, 47.990000000000002, 58.530000000000001, 69.060000000000002, 67.269999999999996, 65.469999999999999, 65.959999999999994, 66.439999999999998, 63.920000000000002, 61.409999999999997, 57.520000000000003, 53.630000000000003, 56.469999999999999, 59.310000000000002, 60.799999999999997, 62.289999999999999}, static Daylight5300_spect = <same as static member of an already seen type>, static Shade7600_spect = <same as static member of an already seen type>, static A2856_spect = <same as static member of an already seen type>, static FluoF1_spect = <same as static member of an already seen type>, static FluoF2_spect = <same as static member of an already seen type>, static FluoF3_spect = <same as static member of an already seen type>, static FluoF4_spect = <same as static member of an already seen type>, static FluoF5_spect = <same as static member of an already seen type>, static FluoF6_spect = <same as static member of an already seen type>, static FluoF7_spect = <same as static member of an already seen type>, static FluoF8_spect = <same as static member of an already seen type>, static FluoF9_spect = <same as static member of an already seen type>, static FluoF10_spect = <same as static member of an already seen type>, static FluoF11_spect = <same as static member of an already seen type>, static FluoF12_spect = <same as static member of an already seen type>, static HMI_spect = <same as static member of an already seen type>, static GTI_spect = <same as static member of an already seen type>, static JudgeIII_spect = <same as static member of an already seen type>, static Solux3500_spect = <same as static member of an already seen type>, static Solux4100_spect = <same as static member of an already seen type>, static Solux4700_spect = <same as static member of an already seen type>, static NG_Solux4700_spect = <same as static member of an already seen type>, static NG_LEDLSI2040_spect = <same as static member of an already seen type>, static NG_CRSSP12WWMR16_spect = <same as static member of an already seen type>, static Flash5500_spect = <same as static member of an already seen type>, static Flash6000_spect = <same as static member of an already seen type>, static Flash6500_spect = <same as static member of an already seen type>, static ColorchechredC3_spect = <same as static member of an already seen type>, static ColorchechOraA2_spect = <same as static member of an already seen type>, static ColorchechYelD3_spect = <same as static member of an already seen type>, static ColorchechGreE2_spect = <same as static member of an already seen type>, static ColorchechGreB3_spect = <same as static member of an already seen type>, static ColorchechCyaF3_spect = <same as static member of an already seen type>, static ColorchechPurD2_spect = <same as static member of an already seen type>, static ColorchechMagE3_spect = <same as static member of an already seen type>, static ColorchechSkiA138_13_14_spect = <same as static member of an already seen type>, static ColorchechGraC4_67_spect = <same as static member of an already seen type>, static ColorchechSkiB166_18_18_spect = <same as static member of an already seen type>, static ColorchechBluC150_m5_m22_spect = <same as static member of an already seen type>, static ColorchechDCBluN881_m7_m14_spect = <same as static member of an already seen type>, static ColorchechSGSkiF763_14_26_spect = <same as static member of an already seen type>, static ColorchechSGSkiK285_11_17_spect = <same as static member of an already seen type>, static ColorchechWhiA496_spect = <same as static member of an already seen type>, static ColorchechGreD1_spect = <same as static member of an already seen type>, static ColorchechSGBlaN3_6_spect = <same as static member of an already seen type>, static JDC468_GraK14_44_spect = <same as static member of an already seen type>, static JDC468_BluH10_spect = <same as static member of an already seen type>, static ColabSkin35_15_17_spect = <same as static member of an already seen type>, static ColabSkin57_22_18_spect = <same as static member of an already seen type>, static ColabSkin40_17_17_spect = <same as static member of an already seen type>, static ColabSkin91_4_14_spect = <same as static member of an already seen type>, static ColabSkin87_8_8_spect = <same as static member of an already seen type>, static ColabSkin89_8_21_spect = <same as static member of an already seen type>, static ColabSkin75_8_4_spect = <same as static member of an already seen type>, static ColabSkin75_10_33_spect = <same as static member of an already seen type>, static ColabSkin65_33_11_spect = <same as static member of an already seen type>, static ColabSkin65_7_24_spect = <same as static member of an already seen type>, static ColabSkin57_19_6_spect = <same as static member of an already seen type>, static ColabSkin57_4_19_spect = <same as static member of an already seen type>, static ColabSkin57_10_28_spect = <same as static member of an already seen type>, static ColabSkin40_7_19_spect = <same as static member of an already seen type>, static ColabSkin40_17_6_spect = <same as static member of an already seen type>, static ColabSkin40_4_11_spect = <same as static member of an already seen type>, static ColabSkin33_6_15_spect = <same as static member of an already seen type>, static ColabSkin33_15_5_spect = <same as static member of an already seen type>, static ColabSkin33_10_15_spect = <same as static member of an already seen type>, static ColabSkin24_5_6_spect = <same as static member of an already seen type>, static ColabSkin26_18_18_spect = <same as static member of an already seen type>, static ColabSkin24_7_5_spect = <same as static member of an already seen type>, static ColabSkin20_4_2_spect = <same as static member of an already seen type>, static ColabSkin98_m2_10_spect = <same as static member of an already seen type>, static ColabSkin90_m1_20_spect = <same as static member of an already seen type>, static ColabSkin95_0_4_spect = <same as static member of an already seen type>, static ColabSkin81_2_14_spect = <same as static member of an already seen type>, static ColabSkin87_3_10_spect = <same as static member of an already seen type>, static ColabSkin77_12_21_spect = <same as static member of an already seen type>, static ColabSkin70_7_32_spect = <same as static member of an already seen type>, static ColabSky60_0_m31_spect = <same as static member of an already seen type>, static ColabSky42_0_m24_spect = <same as static member of an already seen type>}
        rm = 2.3893385085187706
        gm = 2.3894016660491006
        bm = 2.3893281947251976
        mul_lum = 2.3893744062166071
        rmi = 2.38277745
        gmi = 2.38284039
        bmi = 2.3827672
        rwidth = 247
        baseImg = 0x7fffcc001d30
        fw = 247
        fh = 164
        ipf = 
            {lastcutpast = false, lastcxbuf = 1073900030, lastcybuf = 1610612736, lastcount = 1072540691, spotbuffer = 0x3ff435c060000000, monitorTransform = 0x0, gamutWarning = std::unique_ptr<rtengine::GamutWarning> = {get() = 0x0}, params = 0x7fffc0002638, scale = 8.6096666745289792, multiThread = false, lumimul = {0.22250449999999999, 0.716878600000000---Type <return> to continue, or q <return> to quit---
03, 0.060616900000000001}, dnparams = {lcurve = std::vector of length 9, capacity 9 = {1, 0.050000000000000003, 0.14999999999999999, 0.34999999999999998, 0.34999999999999998, 0.55000000000000004, 0.040000000000000001, 0.34999999999999998, 0.34999999999999998}, cccurve = std::vector of length 9, capacity 9 = {1, 0.050000000000000003, 0.5, 0.34999999999999998, 0.34999999999999998, 0.34999999999999998, 0.050000000000000003, 0.34999999999999998, 0.34999999999999998}, enabled = false, enhance = false, median = false, perform = false, luma = 0, Ldetail = 0, chroma = 15, redchro = 0, bluechro = 0, gamma = 1.7, dmethod = {static npos = 18446744073709551615, string_ = "Lab"}, Lmethod = {static npos = 18446744073709551615, string_ = "SLI"}, Cmethod = {static npos = 18446744073709551615, string_ = "MAN"}, C2method = {static npos = 18446744073709551615, string_ = "AUTO"}, smethod = {static npos = 18446744073709551615, string_ = "shal"}, medmethod = {static npos = 18446744073709551615, string_ = "soft"}, methodmed = {static npos = 18446744073709551615, string_ = "none"}, rgbmethod = {static npos = 18446744073709551615, string_ = "soft"}, passes = 1}}
        hist16 = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, data = 0x7fffcc32a3a0, clip = 3, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        expcomp = 0
        bright = 0
        contr = 0
        black = 375
        hlcompr = 70
        hlcomprthresh = 30
        curve1 = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, data = 0x7fffcc36a3c0, clip = 1, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        curve2 = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, data = 0x7fffcc116490, clip = 2, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        curve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, data = 0x7fffcc1564b0, clip = 3, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        satcurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, data = 0x7fffcc1964d0, clip = 3, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        lhskcurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, data = 0x7fffcc1d64f0, clip = 3, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        lumacurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 32768, maxsf = 32768, data = 0x7fffcc3f11c0, clip = 0, size = 32770, upperBound = 32769, owner = 1, maxsv = {32768, 32768, 32768, 32768}, sizev = {32769, 32769, 32769, 32769}, sizeiv = {140741783355393, 140741783355393}, dirty = true}
        clcurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 65534, maxsf = 65534, data = 0x7fffcc4111e0, clip = 3, size = 65536, upperBound = 65535, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}
        clToningcurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        cl2Toningcurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        dummy = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        customToneCurve1 = 
            {_vptr.ToneCurve = 0x55555695cc90 <vtable for rtengine::ToneCurve+16>, lutToneCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {65534, 65534, 65534, 65534}, sizev = {65535, 65535, 65535, 65535}, sizeiv = {281470681808895, 281470681808895}, dirty = true}}
        customToneCurve2 = 
            {_vptr.ToneCurve = 0x55555695cc90 <vtable for rtengine::ToneCurve+16>, lutToneCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, c---Type <return> to continue, or q <return> to quit---
lip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        ctColorCurve = 
          {_vptr.ColorGradientCurve = 0x55555695ea38 <vtable for rtengine::ColorGradientCurve+16>, lut1 = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}, lut2 = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}, lut3 = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}, low = 6.9533269510566604e-310, high = 6.953329290705712e-310}
        ctOpacityCurve = 
            {_vptr.OpacityCurve = 0x55555695ea58 <vtable for rtengine::OpacityCurve+16>, lutOpacityCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        customColCurve1 = 
            {_vptr.ColorAppearance = 0x55555695ea18 <vtable for rtengine::ColorAppearance+16>, lutColCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        customColCurve2 = 
            {_vptr.ColorAppearance = 0x55555695ea18 <vtable for rtengine::ColorAppearance+16>, lutColCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        customColCurve3 = 
            {_vptr.ColorAppearance = 0x55555695ea18 <vtable for rtengine::ColorAppearance+16>, lutColCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        customToneCurvebw1 = 
            {_vptr.ToneCurve = 0x55555695cc90 <vtable for rtengine::ToneCurve+16>, lutToneCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        customToneCurvebw2 = 
            {_vptr.ToneCurve = 0x55555695cc90 <vtable for rtengine::ToneCurve+16>, lutToneCurve = {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}}
        rCurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        gCurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        bCurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        opautili = false
        rrm = 7.3002709612574945e+43
        ggm = 7.3002145486330461e+43
        bbm = 5.5417668474818325e+257
        autor = -9000
        autog = -9000
        autob = -9000
        satLimit = 0.300000012
        satLimitOpacity = 0.99000001
        labView = 0x7fffcc006e50
        dcpProf = 0x7fffcc005070
        as = {data = std::unique_ptr<rtengine::DCPProfile::ApplyState::Data> = {get() = 0x7fffcc001500}}
        histToneCurve = 
          {<rtengine::NonCopyable> = {<No data fields>}, maxs = 0, maxsf = 0, data = 0x0, clip = 0, size = 0, upperBound = 0, owner = 1, maxsv = {0, 0, 0, 0}, sizev = {0, 0, 0, 0}, sizeiv = {0, 0}, dirty = true}
        utili = true
        clcutili = false
        autili = false
---Type <return> to continue, or q <return> to quit---
        butili = false
        ccutili = false
        cclutili = false
        readyImg = 0x7fffcc3abc90
#6  0x0000555555f49217 in Thumbnail::processThumbImage(rtengine::procparams::ProcParams const&, int, double&) (this=0x7fffc0002480, pparams=..., h=164, scale=@0x7fffdd2fd958: 1)
    at /home/fabien/Programmes/rawtherapee-git/rtgui/thumbnail.cc:620
        lock = {<rtengine::NonCopyable> = {<No data fields>}, mutex = @0x7fffc0002480, locked = true}
        image = 0x0
#7  0x0000555555f44995 in ThumbImageUpdater::Impl::processNextJob() (this=0x55555aeeaa70) at /home/fabien/Programmes/rawtherapee-git/rtgui/thumbimageupdater.cc:156
        j = {tbe_ = 0x7fffc0060870, priority_ = 0x7fffc0060a48, upgrade_ = false, listener_ = 0x7fffc0060a58}
        scale = 1
        img = 0x0
        thm = 0x7fffc0002480
#8  0x0000555555f45b60 in sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>::operator()() const (this=0x7fffcc004038)
    at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
#9  0x0000555555f45a5e in sigc::adaptor_functor<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl> >::operator()() const (this=0x7fffcc004030)
    at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#10 0x0000555555f45826 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>, void>::call_it(sigc::internal::slot_rep*) (rep=0x7fffcc004000)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:114
        typed_rep = 0x7fffcc004000
#11 0x00007ffff5a43991 in  () at /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#12 0x00007ffff68cb7d0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff68cae05 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff2a6c6db in start_thread (arg=0x7fffdd2fe700) at pthread_create.c:463
        pd = 0x7fffdd2fe700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140736904292096, -8297726379158738956, 140736904289280, 0, 93825022636672, 140737488344496, 8297661921215834100, 8297715873978705908}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#15 0x00007ffff279588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`
```

**Comment by Beep6581** [comment]
Happens often to me when I create new files using HDRMerge in RT's active folder, or when I save new TIFFs to it.

On a side note, @FM33 I formatted your post to make it more readable - please edit it to see what I did so that you can do it in the future.
