### ISSUE TITLE
Segfault upon selecting noise reduction

### ISSUE THREAD

**Issue by noirsabb** [Beep6581/RawTherapee#4842]
Hi

Just reporting a segfault with a recent nightly build of Rawtherapee. Basically I was trying to denoise an image (via the Noise Reduction option under the Detail pane) for which I had adjusted the exposure compensation by about six stops. I built a debug version of the software and have the stacktrace below. It looks like the program was deallocating unallocated memory in method
rtengine::ImProcFunctions::RGB_denoise of file rtengine/FTblockDN.cc.

I added some checks where I thought the problem was and no more segfault in this instance.

Around line 1746:

            if (numtiles >= 1 && denoiseLuminance) {
                for (int i = 0; i < denoiseNestedLevels * numthreads; ++i) {
                    if (LbloxArray[i]) {
                        fftwf_free(LbloxArray[i]);
                    }
                    if (fLbloxArray[i]) {
                        fftwf_free(fLbloxArray[i]);
                    }
                }
            }

Perhaps it is my particular setup that caused the problem?

About:
```

Version: nightly-717-g080033765
Branch: dev
Commit: 080033765
Commit date: 2018-09-27
Compiler: clang70 7.0.0
Processor: ivybridge
System: Linux (actually FreeBSD)
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: RELEASE
Build flags:  -std=c++11 -march=core-avx2 -Werror=unused-label -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=core-avx2
OpenMP support: ON
MMAP support: ON
```

Stacktrace:
```

jamie@apocalypse:/home/jamie/Desktop/repo-rt/build/DEBUG$ gdb ./rawtherapee
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) r
Starting program: /usr/home/jamie/Desktop/repo-rt/build/DEBUG/rawtherapee 

(process:6043): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.

(rawtherapee:6043): Gtk-WARNING **: Allocating size to gtkmm__GtkPaned 0x81d98f590 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

Program received signal SIGSEGV, Segmentation fault.
0x000000080857df19 in realloc () from /lib/libc.so.7
(gdb) bt
#0  0x000000080857df19 in realloc () from /lib/libc.so.7
#1  0x000000080857e5b1 in free () from /lib/libc.so.7
#2  0x0000000000e15f9f in rtengine::ImProcFunctions::RGB_denoise (this=0x837e5e740, kall=0, src=0x82035f000, dst=0x82035f000, 
    calclum=0x0, ch_M=0x837e62ff4, max_r=0x837e62fac, max_b=0x837e62fd0, isRAW=true, dnparams=@0x7fffd69b0dc8, 
    expcomp=4.7596111297607422, noiseLCurve=@0x7fffd69b13b0, noiseCCurve=@0x7fffd69b1330, nresi=@0x7fffd69b0db0, 
    highresi=@0x7fffd69b0dac) at /home/jamie/Desktop/repo-rt/rtengine/FTblockDN.cc:1746
#3  0x0000000000b1f7fe in rtengine::Crop::update (this=0x82b313300, todo=1023) at /home/jamie/Desktop/repo-rt/rtengine/dcrop.cc:657
#4  0x00000000010276ac in rtengine::ImProcCoordinator::updatePreviewImage (this=0x837e5e680, todo=1023, cropCall=0x0)
    at /home/jamie/Desktop/repo-rt/rtengine/improccoordinator.cc:906
#5  0x000000000102c20a in rtengine::ImProcCoordinator::process (this=0x837e5e680)
    at /home/jamie/Desktop/repo-rt/rtengine/improccoordinator.cc:1424
#6  0x000000000102f5b8 in sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator>::operator() (this=0x82b252f58)
    at mem_fun.h:1991
#7  0x000000000102f539 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator> >::operator() (
    this=0x82b252f50) at adaptor_trait.h:256
#8  0x000000000102f511 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator>, void>::call_it (
    rep=0x82b252f20) at slot.h:114
#9  0x0000000805051d83 in Glib::Thread::create () from /usr/local/lib/libglibmm-2.4.so.1
#10 0x00000008041e640a in g_thread_unref () from /usr/local/lib/libglib-2.0.so.0
#11 0x0000000803757c06 in pthread_create () from /lib/libthr.so.3
#12 0x0000000000000000 in ?? ()
(gdb) up 2
#2  0x0000000000e15f9f in rtengine::ImProcFunctions::RGB_denoise (this=0x837e5e740, kall=0, src=0x82035f000, dst=0x82035f000, 
    calclum=0x0, ch_M=0x837e62ff4, max_r=0x837e62fac, max_b=0x837e62fd0, isRAW=true, dnparams=@0x7fffd69b0dc8, 
    expcomp=4.7596111297607422, noiseLCurve=@0x7fffd69b13b0, noiseCCurve=@0x7fffd69b1330, nresi=@0x7fffd69b0db0, 
    highresi=@0x7fffd69b0dac) at /home/jamie/Desktop/repo-rt/rtengine/FTblockDN.cc:1746
1746                        fftwf_free(LbloxArray[i]);
(gdb) p LbloxArray
$1 = 0x7fffd69af2c0
(gdb) p i          
$2 = 0
(gdb) p LbloxArray[i]
$3 = (float *) 0x4000c
(gdb) p LbloxArray[0]
$4 = (float *) 0x4000c
(gdb) p LbloxArray[1]
$5 = (float *) 0x7fff00000000
(gdb) p 0x4000c
$6 = 262156
(gdb) p (float *)0x4000c 
$7 = (float *) 0x4000c
(gdb) p (float *)(0x4000c)
$8 = (float *) 0x4000c
(gdb) p numtiles
$9 = 1
(gdb) p denoiseLuminance
$10 = false
(gdb) p LbloxArray[1]     
$11 = (float *) 0x7fff00000000
(gdb) p LbloxArray[0]
$12 = (float *) 0x4000c
(gdb) p *LbloxArray[0]
Error accessing memory address 0x4000c: Bad address.
(gdb) q
The program is running.  Exit anyway? (y or n) y

```

**Comment by Beep6581** [comment]
Hi @noirsabb 

> Version: nightly-717-g080033765

That reported version description is not right. To fix it, follow these steps:
https://github.com/Beep6581/RawTherapee/issues/4509#issuecomment-382731056

**Comment by noirsabb** [comment]
Hi

Thanks for the reply. The problem probably was at my end. I cloned a new repository, and got a compilation error. I now recall I fixed the compilation error, but did not initialize the memory allocated. Sorry for the noise.

```
In file included from /usr/home/jamie/Desktop/repo-rt/rtengine/FTblockDN.cc:29:
In file included from /usr/home/jamie/Desktop/repo-rt/rtengine/improcfun.h:33:
In file included from /usr/home/jamie/Desktop/repo-rt/rtengine/dcp.h:32:
In file included from /usr/home/jamie/Desktop/repo-rt/rtengine/curves.h:26:
In file included from /usr/home/jamie/Desktop/repo-rt/rtengine/../rtgui/mycurve.h:26:
In file included from /usr/home/jamie/Desktop/repo-rt/rtengine/../rtgui/coloredbar.h:23:
/usr/home/jamie/Desktop/repo-rt/rtengine/../rtgui/guiutils.h:276:10: warning: 'MyExpander::add' hides overloaded virtual function
      [-Woverloaded-virtual]
    void add  (Gtk::Container& widget, bool setChild = true);
         ^
/usr/local/include/gtkmm-3.0/gtkmm/container.h:191:16: note: hidden overloaded virtual function 'Gtk::Container::add' declared here:
      different number of parameters (1 vs 2)
  virtual void add(Widget& widget);
               ^
/usr/home/jamie/Desktop/repo-rt/rtengine/FTblockDN.cc:808:31: error: variable-sized object may not be initialized
            float *LbloxArray[denoiseNestedLevels * numthreads] = {};
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/home/jamie/Desktop/repo-rt/rtengine/FTblockDN.cc:809:32: error: variable-sized object may not be initialized
            float *fLbloxArray[denoiseNestedLevels * numthreads] = {};
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7 warnings and 2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/jamie/Desktop/repo-rt/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/jamie/Desktop/repo-rt/build
*** Error code 1

Stop.
make: stopped in /usr/home/jamie/Desktop/repo-rt/build
jamie@apocalypse:/usr/home/jamie/Desktop/repo-rt/build$ 
```
