### ISSUE TITLE
Capture Sharpening Auto Radius Segfault

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#5621]
Steps to reproduce:
1. Open the image file.

OR

1. Apply Neutral profile to the image.
2. Open the image in the editor.
3. Enable Capture Sharpening.

Problematic raw file [here](https://filebin.net/yl11pana62ol4tj5).
Capture Sharpening takes a long time to process, then RawTherapee crashes before Capture Sharpening can finish.

Backtrace:
```
Thread 58 "rawtherapee" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffea666700 (LWP 249069)]
LUT<float>::operator[]<float, float, void> (this=0x55555643c100 <rtengine::Color::gamma2curve>, index=-nan(0x400000))
    at RawTherapee/rtengine/LUT.h:453
453             T p1 = data[idx];
(gdb) frame
#0  LUT<float>::operator[]<float, float, void> (this=0x55555643c100 <rtengine::Color::gamma2curve>, index=-nan(0x400000))
    at RawTherapee/rtengine/LUT.h:453
453             T p1 = data[idx];
(gdb) bt
#0  0x0000555555c74b77 in LUT<float>::operator[]<float, float, void>(float) const (this=0x55555643c100 <rtengine::Color::gamma2curve>, index=-nan(0x400000))
    at RawTherapee/rtengine/LUT.h:453
#1  0x0000555555d70eeb in rtengine::ImProcFunctions::_ZN8rtengine15ImProcFunctions7rgbProcEPNS_10ImagefloatEPNS_8LabImageEPNS_13PipetteBufferERK3LUTIfESA_SA_iSA_SA_SA_ffRKNS_18ColorGradientCurveERKNS_12OpacityCurveEbSA_SA_RKNS_9ToneCurveESJ_SJ_SJ_RdSK_SK_RfSL_SL_diiPNS_10DCPProfileERKNS_20DCPProfileApplyStateERS7_IjEmb._omp_fn.0(void) ()
    at RawTherapee/rtengine/improcfun.cc:2528
#2  0x00007ffff5980eee in gomp_thread_start (xdata=<optimized out>) at /build/gcc/src/gcc/libgomp/team.c:123
#3  0x00007ffff59334cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff58622d3 in clone () at /usr/lib/libc.so.6
```
Build information:
```
Version: 5.7-422-g227c2fbba
Branch: dev
Commit: 227c2fbba
Commit date: 2020-01-24
Compiler: cc 9.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Thanatomanic** [comment]
I was not able to replicate the crash, but CS is definitely taking a long time to process.

**Comment by Beep6581** [comment]
Segfault reproduced here in Sabayon using second set of steps (apply neutral,  open,  enable CS):
```
Version: 5.7-423-g24684e5cb
Branch: dev
Commit: 24684e5cb
Commit date: 2020-01-26
Compiler: cc 8.2.0
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

Ping @heckflosse

**Comment by heckflosse** [comment]
looking...

**Comment by heckflosse** [comment]
I can reproduce the segfault. Looking for the culprit now...

**Comment by heckflosse** [comment]
Fixed with https://github.com/Beep6581/RawTherapee/commit/397099c543b47de748d9a12dacc31cb2ff7f535c

**Comment by Lawrence37** [comment]
Fix confirmed.

**Comment by heckflosse** [comment]
@Lawrence37 
> Fix confirmed.

\o/
