### ISSUE TITLE
Memory leak in `rtengine::Crop`

### ISSUE THREAD

**Issue by hfiguiere** [Beep6581/RawTherapee#6721]
**Short description**
Memory leak in `rtengine::Crop`

**Steps to reproduce**

Download the RAW file from https://raw.pixls.us/getfile.php/1018/nice/Canon%20-%20EOS%2020D%20-%20RAW%20(3:2).CR2
You can also use the file listed in #6709 (with the patch). Or almost any other file.

- Build rawtherapee with -DWITH_ASAN=address
- Go to the directory with the file above
- Double click on the file
- Quit RawTherapee

asan report the following leak:

```
Direct leak of 3666016 byte(s) in 1 object(s) allocated from:
    #0 0x7fb91e2bb308 in operator new[](unsigned long) (/lib64/libasan.so.8+0xbb308)
    #1 0x18ecb23 in rtengine::Crop::setCropSizes(int, int, int, int, int, bool) /home/hub/source/RawTherapee/rtengine/dcrop.cc:1922
    #2 0x18d0333 in rtengine::Crop::update(int) /home/hub/source/RawTherapee/rtengine/dcrop.cc:168
    #3 0x18ed445 in rtengine::Crop::fullUpdate() /home/hub/source/RawTherapee/rtengine/dcrop.cc:1999
    #4 0x734ce1 in sigc::bound_mem_functor0<void, rtengine::DetailedCrop>::operator()() const /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
    #5 0x734a6b in sigc::adaptor_functor<sigc::bound_mem_functor0<void, rtengine::DetailedCrop> >::operator()() const /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
    #6 0x7343c0 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, rtengine::DetailedCrop>, void>::call_it(sigc::internal::slot_rep*) /usr/include/sigc++-2.0/sigc++/functors/slot.h:136
    #7 0x7fb91d173aa9 in call_thread_entry_slot.lto_priv.0 (/lib64/libglibmm-2.4.so.1+0x5aaa9)

```

**Expected behavior**
No leak (there are others smaller still, bit the one above is gone.

**Additional information**
```
Version: 5.9-128-g5481a8bbe
Branch: dev
Commit: 5481a8bbe
Commit date: 2023-03-20
Compiler: cc 12.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.3.0
Build type: Debug
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -fsanitize=address -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:   -fsanitize=address
OpenMP support: ON
MMAP support: ON
Build OS: Linux 6.1.14-200.fc37.x86_64 x86_64
Build date: Mon, 20 Mar 2023 21:16:15 +0000 UTC
Build epoch: 1679346975
Build UUID: 1aa7869e-e061-40d2-8944-151ff8f32d18
```

**Comment by hfiguiere** [comment]
See PR #6722

**Comment by ValeZAA** [comment]
>there are others smaller still, bit the one above is gone.

Is it all good now?

**Comment by ValeZAA** [comment]
I meant those smaller leaks, not the main leak.

**Comment by hfiguiere** [comment]
see https://github.com/Beep6581/RawTherapee/issues/6733

I just mentionned they exist as this one had a fix. So when testing the fix that it was expected there are others.
